---
title: " "
output: pdf_document
header-includes:
  - \usepackage{float}
  - \usepackage{sectsty}
editor_options: 
  markdown: 
    wrap: 72
bibliography: references.bib
---

# Introduction

The association between greater socioeconomic resources and better health is well documented. Higher socioeconomic status is associated with better self-reported health ((Link et al. 2008; Meyer, Castro-Schilo, and Aguilar-Gaxiola 2014), better mental health (Hill, Cook, and Whitfield 2014; Pinxten and Lievens 2014; Ross and Mirowsky 2006), lower mortality risk (Bosworth 2018; Duncan et al. 2002; Laaksonen et al. 2007; Link et al. 2008; Lleras-Muney 2005; Ross, Masters, and Hummer 2012), lower infant mortality rates (Bleich et al. 2012), lower rates of obesity (Bleich et al. 2012; Cutler and Lleras-Muney 2006, 2010; Mirowsky and Ross 1998; Ross and Mirowsky 1999), fewer chronic conditions (Bleich et al. 2012; Herd, Goesling, and House 2007; Link et al. 2008), and fewer functional limitations (Herd et al. 2007). Health behaviors are responsible for part of this association (Adler et al. 1994; Adler and Rehkopf 2008; Brunello et al. 2016; Burdette and Hill 2008; Lantz et al. 1998, 2001). Higher socioeconomic status is associated with increased physical activity, better diet, healthier alcohol consumption, non-smoking, more frequent seatbelt use, utilization of preventive healthcare, and use of smoke detectors (Bleich et al. 2012; Cutler and Lleras-Muney 2010; Meyer et al. 2014; Pampel, Krueger, and Denney 2010). While the study of health behaviors has made significant contributions to our understanding of associations between social statuses and health (Pampel et al. 2010), there is now substantial evidence that health behaviors cluster to form discernible health lifestyles (Andrews, Hill, and Cockerham 2017; Berrigan et al. 2003; Burke et al. 1997; Cockerham 2007; Dodd et al. 2010; Mize 2017; Patterson, Haines, and Popkin 1994; Saint Onge and Krueger 2017; Schuit et al. 2002; de Vries et al. 2008). Patterns of health behaviors occur in much higher proportions than would be expected if health behaviors were independent (Berrigan et al. 2003). The clustering of health behaviors has been well supported by studies utilizing a variety of methods to identify patterns across behaviors (Andrews et al. 2017; Burdette et al. 2017; Dodd et al. 2010; Hill et al. 2007; Lawrence, Mollborn, and Hummer 2017; Mize 2017; Mollborn et al. 2014; Patterson et al. 1994; Saint Onge and Krueger 2017; de Vries et al. 2008).

Recent studies have revealed that health behaviors cluster into health lifestyles in counterintuitive ways. Even in studies of pairs of behaviors, it is apparent that by isolating analyses to single behaviors we risk misinterpreting the causes and consequences of health behavior. In a clinical study, participants who simultaneously began dietary and physical activity interventions continued to meet health recommendations at 12 months. Participants who began the interventions sequentially did not meet health recommendations at 12 months (King et al. 2013). In a cross-sectional study, researchers found a positive association between drinking and physical activity (French, Popovici, and Maclean 2009).

With the inclusion of many health behaviors, the complexity of health lifestyles reveals itself further. Recent latent class analyses of multiple health behaviors have confirmed the existence of distinct, multi-dimensional health lifestyles (Burdette et al. 2017; Lawrence et al. 2017; Mize 2017; Saint Onge and Krueger 2017). Within this new research stream, however, the study of health lifestyles has been largely restricted to behaviors of concern traditionally to public health. The most common combination of behaviors within lifestyles research is alcohol use, smoking, diet, and exercise. An entire subset of health behaviors, the use of complementary and alternative medicines (CAMs), has been virtually ignored. 

In this dissertation, I will address this research gap using longitudinal data from a nationally representative sample of U.S. adults to examine the effects of socioeconomic status on CAM use. In the sections below, I will review research on CAM use and its association with socioeconomic status, as well as motivations for use. Following a review of relevant theoretical perspectives on health lifestyles and SES, I will discuss the contributions of this dissertation to the literature on health lifestyles. In the final sections of this proposal, I will describe the data and methodology for three studies. 

# General CAM Use

About a third of U.S. adults report the use of any CAMs (Barnes, Bloom, and Nahin 2008; Clarke et al. 2015), and CAM use appears to be increasing with younger cohorts (Kessler et al. 2001). Clarke et al. (2015) found that out of the 20 CAM behaviors included in the National Health Interview Survey (NHIS) CAM Supplement collected in 2002, 2007, and 2012, the use of nonvitamin, nonmineral dietary supplements was highest across all three time points, followed by deep breathing exercises. The use of yoga, tai chi, and qi gong became more popular over time, and meditation ranked in the top 5 most popular approaches at each time point. The use of other CAMs, including Ayurveda, biofeedback, guided imagery hypnosis, and energy health therapy, have not changed significantly over time. 

The National Center for Complementary and Integrative Medicine (NCCIM) classifies CAMs into five broad categories: biologically based therapies (including herbal medicine, vitamin use, and special diets), alternative medical systems (including acupuncture and homeopathy), manipulative body-based therapies (including massage therapy, exercise and movement therapies, and chiropractic therapy), mind-body therapies (including hypnosis, imagery techniques, and meditation), and energy healing therapies (use of hands to manipulate and balance energy fields). Barnes et al. (2008) found that 19.9% of adults report using biologically based therapies, 19.2% report using mind-body therapies, 3.4% report using alternative medical systems, 0.5% report using energy healing therapy, and 15.2% report using manipulative and body-based therapies. 

# Trends in CAM Use by SES

Those with higher levels of education tend to use CAMs at higher rates (Barnes et al. 2008; Clarke et al. 2015; Honda and Jacobson 2005; Mbizo et al. 2018; Ni, Simile, and Hardy 2002; Upchurch et al. 2018). Clarke et al. (2015) found that in 2002, 18.6% of adults with less than a high school diploma reported CAM use, followed by 18.8% in 2007, and 15.6% in 2012. In 2002, 26.6% of adults with a high school diploma or General Educational Development high school equivalency diploma (GED) reported CAM use, followed by 28.1% in 2007, and 24.4% in 2012. In 2002, 35.6% of adults with some college education reported CAM use, followed by 41.3% in 2007, and 36.5% in 2012. In 2002, 42.1% of adults with a college degree or higher reported CAM use, followed by 46.7% in 2007, and 42.6% in 2012 (Clarke et al. 2015). Barnes et al. (2008) reported the following rates of CAM use in 2007 for six educational categories: 20.8% of adults with less than a high school diploma, 31.0% of adults with a high school diploma or equivalent, 45% of adults with some college, 47.2% of adults with an Associates degree, 49.6% of those with a Bachelors, and 55.4% of those with a Masters, Doctorate, or Professional degree. Hildreth and Elman (2007) also found that use of any CAMs increased by level of education; however, among those that used any CAM in the past year, the authors found a threshold effect. Only those with a college degree or more used significantly more types of CAMs compared to those without a high school diploma.   

Findings on the rate of CAM use by income have been mixed across studies. Mbizo et al. (2018) found that overall CAM use was significantly different across five income categories. Overall CAM use increased by income across the first four income categories; however, the highest income category ($75,000+) only reported greater use than the lowest income category (<$20,000). Among those who have utilized CAMs in the past year, Hildreth and Elman (2007) did not find a significant association between income and any CAM use or number of CAMs utilized. Clarke et al. (2015) found that CAM use was higher for not-poor adults (measured as poverty-income ratio), followed by near poor, and lowest among the poor across 2002, 2007, and 2012. CAM use ranged from 20.6% in 2012 to 26.6% in 2002 among the poor, from 25.5% in 2012 to 27.7% in 2002 among the near poor, and 36.8% in 2002 to 40.3% in 2007 among the not poor. Ni et al. (2002)found that those making less than $20,000 per year reported less CAM use than those making $20,000 per year or more.  

# CAM Efficacy

Evidence of efficacy varies across CAMs and is dependent on the health
conditions reviewed. In the following sections, I will review evidence
of CAM efficacy for four categories of CAMs. These categories reflect
the factors identified in an exploratory factor analysis that will be
reviewed in Chapter... Categories of CAMs include mind-body medicine,
alternative medical systems, physical and nutritional approaches, and
manipulative treatments.

## Mind-Body Medicines

Mind-body medicines or practices represent an array of techniques that
aim to connect the body and mind to improve health and wellness.
Mind-body medicines include prayer or spiritual healing, energy healing,
imagery techniques, relaxation and meditation techniques, and hypnosis.

Reiki is a form of energy healing that involves noninvasive,
nonmanipulative touch. It is performed by a practitioner who has been
"attuned" by a Reiki master. When performed, the practitioner lightly
lays their hands on or just above the body, working in a slow
progression about the body. In a review of clinical studies conducted
between 1998 and 2016, @mcmanus2017 identified 13 studies that compared
the effects of Reiki to a sham Reiki/placebo. Eight of the 13 studies
found that Reiki was more effective than a placebo. The authors found
that Reiki performed better than placebos at producing physical
relaxation [@witte2001 ; @baldwin2006; @baldwin2008;
@díaz-rodríguez2011; @salles2014]. Reiki has been found to be more
effective at reducing pain, depression, and anxiety among chronically
ill patients compared to a placebo, progressive muscle relaxation, and a
rest control group [@dressen1998]. Similarly, Reiki has been found to
decrease depression among older adults living in nursing homes compared
to a placebo and control group [@erdogan2016]. Imagery techniques, also
known as guided imagery or mental imagery, are quasi-perceptual
experiences. They involve imagining a scene or experience in the "mind's
eye" absent external stimuli. Imagery techniques are often used to
reduce stress [@clarke2015]. Experimental studies have also found
imagery techniques can reduce pain perception and increase pain
tolerance [@milling2003; @alden2001]. Studies on the effectiveness of
imagery techniques for treating asthma symptoms have yielded mixed
results. @freeman2005 utilize an experimental design to compare the
effects of imagery techniques and critical thinking in combination with
asthma education on outcomes among asthma patients. In combination with
asthma education, the imagery technique group created biologically
targeted imagery (BTI) that represented healthy lung function.
Participants in the critical thinking asthma management group (CTAM)
created an individualized plan that emphasized removal of allergy and
asthma triggers from the home and work environment, family support, and
stress reduction. The BTI group experienced improvement in wheezing,
anxiety reduction, hostility reduction, depression, uncertainty,
tiredness, and confusion. Notably, the BTI group experienced a
significant reduction in wheezing and more quickly than the CTAM group.
In another experiemental study of asthma patients, @epstein2004 found no
significant difference between the guided imagery group and the control
group in symptoms.

Meditation is a Buddhist practice that aims to increase awareness of the
present moment and one's experience. It has been investigated as a
possible treatment for chronic pain, showing promising evidence of its
effectiveness. In a randomized controlled trial of 282 participants,
@morone2017 found that an 8 week mindfulness based stress reduction
program effectively reduced self-reported pain disability among adults
with low back pain, though the effects of the program did not hold at
the 6 month follow-up. @garland2014 tested the effectiveness of an 8
week mindfulness intervention program for treating chronic pain in
opioid-abusing patients in a randomized controlled trial. The authors
found that pain severity and pain interference were significantly
reduced in the treatment group, and that the mindfulness intervention
was more effective than enrollment in a support group. @cherkin2016
compared a mindfulness based stress reduction program, cognitive
behavioral therapy, and usual care in a study of 342 adults ages 20 to
70 years old with chronic low back pain. The authors found that the
mindfulness intervention was more effective at improving back pain and
functional limitations at 26 weeks compared to usual care. Mindfulness
techniques have also been examined as a possible treatment for
headaches, though mindfulness techniques did not reduce the frequency,
length, or pain intensity of headaches compared to usual care
[@anheyer2019]. Imagery techniques have similarly been studied for their
possible utility as a treatment for pain and has been found to be
possibly effective treating pain in postoperative orthopedic patients
[@carpenter2017] and cancer patients [@depaolis2019].

Mind-body practices have been found to be largely effective in treating
anxiety, depression, and stress [@breedvelt2019; @cillessen2019]. In a
sample of adults experiencing moderate sleep disturbances, @black2015
found that mindfulness meditation improved depression symptoms in
addition to improving sleep and fatigue. Meditation has also been found
to lower anxiety and depression in patients with chronic heart failure
[@sullivan2009; @jayadevappa2007], patients experiencing acute
depression [@strauss2014], and patients with treatment resistant
depression [@eisendrath2016]. Imagery techniques have been found to
decrease anxiety and depression in the general population[@klaus2000;
@nguyen2018] as well as in patients with cancer [@depaolis2019;
@mahdizadeh2019], chronic heart failure [@chang2004], and undergoing
hemodialysis [@beizaee2018].

## Alternative Medicines

Alternative medicines or alternative medical systems reflect CAMs based
on complete systems of theory and practice. These include homeopathy,
herbal therapy, and acupuncture.

Homeopathy is a medical system that originated in Germany more than 200
years ago. There are two underlying theories to homeopathy. The first is "like cures like," which posits that a disease may be treated with a substance that "produces similar symptoms in healthy people." The second is the "law of minimum dose," which posits that lower doses of medication increase effectiveness. Homeopathic treatments consist of plant products, minerals, and animal products. Treatments are individualized to suit each person. Systematic reviews and meta-analyses of randomized controlled trials have found little to no support for homeopathy's effectiveness. @shang2005 conducted a meta-analysis comparing placebo-controlled trials of homeopathy and conventional medicine. In examination of the full sample of trials (110 homeopathy, 110 conventional medicine), smaller trials of lower quality tended to show greater treatment effects compared to larger and higher quality trials. When analyses were limited to larger trials of higher quality (21 homeopathy trials and 9 conventional medicine trials) homeopathy failed to outperform the placebo while the effects of conventional medicine remained. The authors conclude that reported treatment effects for homeopathy are explained by inadequate methodology and selective publication. @altunç2007 conducted a systematic review of homeopathic therapeutic and prevention interventions for childhood and adolescent ailments. The authors included 16 double-blind placebo controlled trials assessing 9 different conditions. Evidence for effective treatment of attention deficit/hyperactivity disorder and acute childhood diarrhea were mixed. In trials concerned with adenoid vegetation, asthma, and upper respiratory tract infection, homeopathy did not perform better
than the placebo. Single trials failed to demonstrate effective
treatment of conjunctivitis and warts. Studies did find some support for
effective treatment of acute otitis media and postoperative
pain-agitation syndrome, though the authors of the review make the point
that these results are in need of replication. Similarly, a review of 11
independent systematic reviews did not provide strong evidence for the
effectiveness of homeopathy [@ernst2002]. Indeed the more rigorous the
trial the smaller the effects sizes became. Despite the lack of
evidence, practitioners and users of homeopathy swear by its
effectiveness and present plenty of anecdotal evidence. @ernst2008
posits that the answer to this contradiction is likely either due to a
placebo effect or the fact that sometimes symptoms simply improve on
their own regardless of treatment.

Herbal therapy refers to the use of plants to improve health and treat
disease. It is not possible to make generalizations about herbal
therapy's overall effectiveness. Each herb must be tested for its own
effectiveness in treatment and prevention of specific diseases
[@ernst2005]. Most have not been subjected to extensive clinical
testing, though some of the more popular herbal medicines have been
investigated for effectiveness, including garlic, ginkgo biloba,
ginseng, echinacea, St. John's Wort, and ginger.

Garlic is used for medicinal purposes in dried and powdered forms as
well as extracted oils. It's anti-bacterial, anti-viral, anti-fungal, anti-hypertensive, blood-glucose lowering anti-thrombotic, anti-mutagenic, and anti-platelet activities have been identified [@ernst2005]. Randomized
controlled trials have demonstrated garlic's effectiveness at reducing
total cholesterol and low-density lipoprotien, though a meta-analysis of
13 randomized controlled trials found only a small positive effect that
became non-significant when only high quality trials were included in
analysis [@stevinson]. With regard to blood pressure, there is evidence
garlic has a small anti-hypertensive effect [@silagy1994] and may
prevent the development of arteriosclerosis [@breithaupt-grögler1997]. A
meta-analysis of 25 randomized controlled trials showed that garlic
preparations were more effects in reducing blood pressure among people
with hypertension compared to a placebo [@ried2008]. @borek discusses
garlic's potential to prevent disease due to its high antioxidant
activity and high content of organosulfur compounds, noting that aged
garlic extract hasbeen shown to modulate cardiovascular risk factors.
The author suggests that the cardiovascular protection provided by aged
garlic extract may also protect the brain against neurodegenerative
conditions such as dementia and Alzheimer's disease. The organosulfur
compounds found in garlic have been shown to eradicate brain cancer
cells [@das2007]. An observational study of the relationship between raw
garlic consumption and lung cancer in a Chinese population between the
years 2003 and 2010 found that consumption of raw garlic 2 or more times
per week was associated with a 46% decrease in odds of developing lung
cancer [@jin2013].

Ginkgo biloba has been promoted as a supplement for conditions including
anxiety, allergies, dementia, eye problems, peripheral artery disease,
and tinnitus [@ernst1999], though overall evidence for ginkgo in
treating health conditions is weak
[@nationalcenterforcomplementaryandalternativemedicine]. Ginkgo biloba
has been shown to be effective in delaying clinical deterioration of
dementia in patients and to bring about symptom improvement
[@ernst1999], though it has not been determined whether the herb also
improves cognitive function in healthy individuals [@canter2007].

Ginseng has been the subject of many studies on effectiveness for a
variety of health purposes. A systematic review of randomized controlled
trials investigating the health benefits of ginseng found evidence that
ginseng improves glucose metabolism and moderates immune system response
[@shergis2013]. Ginseng has been found to be assist in maintaining
homeostasis of the immune system, enhancing resistance to illness or
microbial attacks through the regulation of the immune system [@wee2011]. Thus it has been suggested that ginseng has beneficial effects on controlling inflammatory diseases and microbial infections [@kang2012]. Ginger has also shown promise as a preventive of cancer [@wee2011; @helmes2004]. Ginseng consumption has been associated with lower risk of stomach, lung, liver, pancreas, ovarian, colon, and oral cancer [@yun2003]. Ginseng may also be effective in treating type 2 diabetes [@wee2011]. Studies in animals have shown that ginseng possesses anti-hyperglycemic activity [@kimura1981; @chung2001; @dey2003]. Studies have also shown that ginseng use decreases fasting glucose, reduces body weight, and increases glucose utilization and insulin regulation among diabetic patients [@sotaniemi1995; @vuksan2008]. Ginseng may also protect against neurodegenerative diseases such as Alzheimer's [@wee2011].

Studies on the health benefits of echinacea have largely focused on its
possible effectiveness in the prevention and treatment of upper
respiratory tract infections. It is believed that echinacea stimulates
the immune system
[@nationalcenterforcomplementaryandalternativemedicine]. There is
evidence that echinacea may protect against upper respiratory infections
but does not reduce the duration of infection [@barrett2010].
@karsch-völk2014 reviewed 24 double-blind trials examining echinacea's
possible preventive and therapeutic uses. The authors found evidence of
some risk reduction in prevention trials, however only 1 of 7 treatment
trials showed a significant effect in reducing the duration of an upper
respiratory infection compared to a placebo. In prevention trials
reviewed by @melchart1999 there was a significantly lower incidence of
infection in treatment groups compared to a placebo for some studies,
while others only found a non-significant trend in favor of treatment
groups. The authors did not find evidence that echinacea reduced the
severity of infections. A recent review of randomized double-blind
placebo controlled trials found evidence of a preventive effect on the
incidence of upper respiratory tract infections but no evidence of an
effect on the duration of infection [@david2019].

St. John's Wort has most commonly been recommended for treating
depression, though it has also been suggested as treatment for
menopausal symptoms, attention-deficit hyperactivity disorder (ADHD),
somatic symptom disorder, and obsessive-compulsive disorder (OCD)
[@nationalcenterforcomplementaryandalternativemedicine]. @apaydin2016
reviewed 35 randomized controlled trials that examine the effects of 4
week administration of St. John's Wort on depression compared to a
placebo or an active control among adults with major depressive
disorder. The authors found no difference in treatment effectiveness for
the St. John's Wort treatment groups compare to participants on
antidepressants, indicating that St. John's Wort may be as effective as
antidepressant medications in treating depression. The St. John's Wort
participants were less likely than participants taking antidepressants
to experience adverse events. Similarly, a review of 27 clinical trials
comparing St. John's Wort to SSRIs found St. John's Wort to be as
effective and safe in the treatment of depression as SSRIs in patients
with mild to moderate depression [@ng2017]. @geller2007 found St. John's
Wort to be effective in treating mood and anxiety in menopausal women.
Finally, hyperforin and hypericin, found in St. John's Wort, have been
shown to have anticancer properties [@you2018; @klemow2011].

The efficacy of ginger root in treating and preventing has been studied
for many health outcomes. Ginger root is very high in total antioxidants
[@halvorsen2002]. Oxidative stress is associated with numerous diseases,
thus ginger's antioxidant properties have been put forth as a possible
explanation for associated health benefits [@aeschbach1994; @ahmad2000].
Ginger root has been found to decrease inflammation, swelling, and pain
[@young2005; @minghetti2007; @eldershaw1992; @ueki2008]. Due to its
anti-inflammatory effect, ginger has been proposed as a possible
treatment against inflammation, osteoarthritis, and rheumatism
[@reginster2000], though evidence of its effectiveness has been
inconsistent [@marcus2001]. Ginger has also been investigated for its
anticarcinogenic activities. It's effectiveness in prevention and
suppression of cancer growth has been explored in lymphoma, hepatoma,
colorectal cancer, breast cancer, skin cancer, liver cancer, and bladder
cancer [@bode2011]. Ginger may be effective at treating aspects of
cardiovascular disease due to its anti-inflammatory, anxioxidant,
anti-platelet, hypotensive, and hypolipidemic effects, though more human
trials are necessary [@nicoll2009]. Ginger has been suggested as a
possible treatment for asthma. Compounds capable of suppressing allergic
reactions found in ginger rhizomes may be used to treat and prevent
allergic diseases [@chen2009]. Lastly, ginger has been explored for its
anti-diabetic effects [@bode2011]. A meta-analysis of 5 randomized
controlled trials found that ginger root supplementation significantly
lowered blood glucose and hemoglobin A1c levels, but did not
significantly lower fasting blood insulin or homeostatic model
assessment-insulin resistance [@daily2015].

Acupuncture is a traditional Chinese medicine in which the practitioner
stimulates specific points in the body typically through the insertion
of thin needles. One of the primary applications studied for acupuncture
has been chronic pain. @vickers2014 completed a meta-analysis of 29
clinical trials that included comparisons of the effectiveness of
acupuncture to no acupuncture and sham acupuncture controls for reducing
pain in a variety of pain conditions. Sham acupuncture is frequently
used as a control in studies to test the theory behind acupuncture. In
sham acupuncture needles are still inserted into patients skin, but are
not inserted as deep as in acupuncture and are not used at the points in
the body specified by traditional acupuncture. Acupuncture was
associated with greater decreases in pain compared to both no
acupuncture and sham acupuncture controls for all pain conditions,
though differences in reduction were smaller between acupuncture and
sham acupuncture compared to acupuncture and no acupuncture controls. In
a randomized controlled trial of 282 patients ages 50 and older with
chronic knee pain, needle and laser acupuncture did not significantly
reduce knee pain or improve function after 12 weeks of treatment
compared to sham acupuncture. Compared to a no acupuncture control
group, needle and laser acupuncture were associated with a modest
improvement in pain and function [@hinman2015]. Acupuncture has shown
promise as a treatment for chronic neck pain. @becker-witt2004 conducted
a randomized controlled trial of 13,846 patients ages 18 and older with
chronic neck pain. Participants were randomly assigned to the treatment
group (n = 1,753) or no acupuncture control group (n = 1698). 10,395
patients did not consent to randomization and were given acupuncture
treatment. The treatment group received up to 15 acupuncture sessions
over the course of 3 months. Following three months of treatment, the
treatment group experienced a greater reduction in neck pain and
disability compared to the control group. Quality of life also differed
significantly between the control and treatment group, favoring the
acupuncture treatment group. There were no differences between the
randomly assigned acupuncture treatment group and the participants who
declined randomization and received acupuncture care.

Acupuncture is widely used for treating low back pain, the second most
frequently reported reason for seeing a physician [@manheimer2005].
@cherkin2009 completed a randomized controlled trials of 638 adults with
chronic low back pain. Participants were randomly assigned to one of
four groups: individualized acupuncture, standardized acupuncture,
simulated acupuncture, and usual care. Participants were given 10
treatments over the course of 7 weeks. At week 8, all treatment groups
experienced a reduction in back-related dysfunction superior to usual
care. These results indicate that placement of the needling sites is
unimportant in producing effects, raising questions about the mechanisms
by which acupuncture influences outcomes. It is possible the results
represent a placebo effect. Results from meta-analyses have been mixed
on verifying whether individualized acupuncture performs better than
sham acupuncture. A systematic review of 23 trials of 6359 participants
found that acupuncture was moderately more effective than no treatment
for relieving low back pain, but was not significantly more effective
compared to sham acupuncture. Another meta-analysis of 33 randomized
controlled trials found that acupuncture is significantly more effective
in producing short-term relief of chronic low back pain compared to sham
acupuncture and no treatment [@manheimer2005].

The current research available on acupuncture's effectiveness in
treating chronic headaches demonstrates that acupuncture is associated
with improvement in clinical outcomes compared to usual care, medical
therapy, and sham acupuncture [@coeytaux2016]. A meta-analysis of 22
trials of 4419 participants found that acupuncture is beneficial in the
treatment of acute migraine attacks on its own or in addition to routine
care. Results suggested that acupuncture is at least as effective, and
possibly more effective, than prophylactic drug treatments and has fewer
adverse effects [@linde2015]. @linde2016 conducted a review of 12 trials
of 2349 participants comparing acupuncture to no treatment and sham
acupuncture for the prevention of tension-type headaches. In trials
comparing acupuncture with routine or usual care, a greater proportion
of participants in the acupuncture groups experienced at least a 50%
reduction in headache frequency compared to control groups. In trials
comparing acupuncture to sham acupuncture, a greater proportion of
participants in the acupuncture group experienced at least a 50%
reduction in headache frequency compared to the sham group following
treatment (51% compared to 43% respectively). Results six months after
treatment were similar. @sun2008 conducted a systematic review of 31
randomized controlled trials of adults experiencing chronic headaches
such as migraines, tension-type headaches, or both. Acupuncture was
compared to sham acupuncture and medication therapy. The authors
examined acupuncture's effect on headache intensity, headache frequency,
and response rate at early and late follow up periods. The authors found
that response rates were significantly higher in the acupuncture group
compared to the sham acupuncture group at early and late follow up
periods. The authors also found that acupuncture produced a greater
reduction in headache intensity and headache frequency and greater improvement in physical functioning and response rate compared to medication therapy.

Acupuncture has been studied extensively for its possible utility as a
treatment for depression. Several systematic reviews and meta-analyses
have been published examining acupuncture's effectiveness in treating
depression compared to no treatment, usual care, sham acupuncture, and
antidepressant medication. @smith2018 found that acupuncture was
moderately more effective in reducing depression symptoms compared to no
treatment. @zhang2010 similarly found that acupuncture improved
depression symptoms in patients with post-stroke depression compared to
no treatment. In contrast, @mukaino2005 and @leo2007 did not find a
significant effect for acupuncture in treating depression compared to no
treatment in their meta-analyses. Studies have provided support for
acupuncture's effectiveness over usual care [@smith2018; @armour2019].
Evidence of acupuncture's effectiveness in reducing depression symptoms
compared to sham acupuncture has been mixed with some studies finding
acupuncture to be more effective [@smith2018], others finding
inconclusive evidence [@mukaino2005], and others finding no significant
difference in effects [@zhang2010; @leo2007]. @smith2018 found
acupuncture to be slightly more beneficial compared to medication
therapy, though the authors note that there was substantial variation
across studies depending on the class of medication and mode of
acupuncture stimulation. Compare to medication, @zhang2010 found that
acupuncture led to better improvements in clinical outcomes symptom
severity in patients with post-stroke depression. In the overall
meta-analysis, the effectiveness of acupuncture was comparable to
antidepressants alone. @mukaino2005 and @leo2007's analyses showed
similar patterns. Results from @armour2019's meta-analysis showed that
acupuncture resulted in significantly greater reductions in depression
severity when used as an additional therapy to anti-depressant
medication. @mukaino2005 on the other hand report that evidence of
acupuncture as an effective adjunct therapy to antidepressant medication
is inconclusive

It has been suggested that acupuncture may be an effective treatment for
asthma, however the quality of randomized controlled trials have been
low and further investigation is necessary to draw conclusions about its
effects [@zhang2012].

## Physical and Nutritional Approaches 

Physical and nutritional approaches represent another subset of CAMs,
including vitamin supplementation, exercise and movement therapy, and
special diet. Below I review evidence from randomized controlled trials
and epidemiological studies on the effectiveness of each approach in
preventing and treating various health conditions.

There are many different vitamins in use in the United States. In this
section I focus on the use and effectiveness of multivitamin and
multimineral (MVMM) supplements. Studies in this literature have
investigated the use of MVMM supplementation in the prevention and
treatment of cardiovascular disease (CVD), cancer, stroke, infection,
and blood pressure, as well as it's relationship to all-cause mortality.
In a review of 18 studies, including randomized controlled trials and
prospective cohort studies, @kim2018 did not find evidence of an
association between MVMM supplementation and stroke mortality or stroke
incidence in the general population. A meta-analysis of 20 randomized
controlled trials testing the relationship between MVMM supplementation
and infection showed no significant difference in the number of
infection episodes among older adults who received MVMM supplementation
and those who did not [@stephen2006]. Among other adult groups studied,
the authors observed significantly fewer episodes of infection in adults
who received MVMM supplementation. Supplementation was found to be more
beneficial among older adults who are undernourished and supplemented
for more than 6 months. @li2018 conducted a meta-analysis of 12
randomized controlled trials investigating the effect of MVMM
supplementation on blood pressure. Results show that MVMM
supplementation lowered systolic and diastolic blood pressure. Further
subgroup analysis reveals that the lowering effect of MVMM
supplementation on blood pressure is only significant in participants
with chronic disease, not in healthy participants. Additionally, the
authors found no effect of MVMM supplementation on risk of hypertension
among participants who had normal blood pressure at baseline. The
authors conclude that MVMM supplementation may be an effective treatment
for lowering blood pressure in patients with chronic disease, but
caution that further investigation is necessary. Drawing on data from
the National Health and Nutrition Examination Survey, @wallace2019
examine the relationship between MVMM supplementation and micronutrient
intakes and inadequacies among middle-aged and older adults in the
United States. The authors found that compared with nutrient intake from
food alone, sporadic MVMM supplementation was associated with a
significant increase in usual intakes of 13 of the 18 micronutrients
assessed. Among those who use MVMM supplementation regularly, the
authors observed significant increases in the usual intakes of calcium
and vitamin K in addition to the 13 micronutrients observed in sporadic
users. Some evidence of a reduced risk of all-cause mortality associated
with MVMM supplementation has been found in prevention trials
[@macpherson2013]. A randomized controlled trial comparing daily
consumption of a combination of antioxidant vitamins and minerals to a
placebo found an association between lower-dose antioxidant
supplementation and lower all-cause mortality in men but not women at a
7.5 year follow up [@hercberg2004].

Evidence of a relationship between MVMM supplementation and CVD
incidence is overall weak. @alexander2013 review results from 12 cohort
studies and 3 primary prevention randomized controlled trials of the
effect of MVMM supplementation on CVD incidence in healthy adults. The
results of 2 randomized controlled trials show that MVMM is associated
with a lowered incidence of CVD, however the observational
epidemiological studies did not confirm this association. @kim2018 found
that MVMM was associated with lower risk of cardiovascular heart disease
(CHD) incidence, though this relationship did not hold in subgroup
analyses of randomized controlled trials. @fortmann2013 review 103
articles representing 26 studies on MVMM supplementation. The authors
report that a majority of the studies did not show a preventive effect
of MVMM supplementation on CVD incidence in healthy populations. In a
recommendation statement published in the Annals of Internal Medicine in
2014, the U.S. Preventive Services Task Force concluded that the current
evidence was not sufficient to assess the benefits and harms of MVMM
supplementation for the prevention of CVD [@moyer2014].

While some preventive effects against cancer have been found for MVMM
supplementation, this effect appears to be limited to men. @hercberg2004
conducted a randomized controlled trial comparing daily consumption of a
combination of antioxidant vitamins and minerals (ascorbic acid, vitamin
E, beta carotene, selenium, and zinc) to a placebo. The authors found
that lower-dose antioxidant supplementation lowered total cancer
incidence in men but not women at 7.5 year follow up. The authors
suggest that supplementation may be more effective in men due to their
lower baseline status of certain antioxidants, especially beta-carotene.
@gaziano2012 conducted a large scale, randomized, double-blind, placebo
controlled trial of 14,641 male U.S. physicians 50 years or older at
baseline. The study began in 1997 with follow up continuing through
2011. The authors observed a statistically significant reduction in
incidence of total cancer in the treatment group though there was no
effect observed for prostate cancer, colorectal cancer, or other
site-specific cancers. The authors did not observe a significant
difference in risk of cancer mortality between the treatment and placebo
groups. Two randomized controlled trials of generally healthy adults
reviewed by @alexander2013 found a lower incidence of cancer in the MVMM
supplementation group, though this association was not confirmed in the
observational epidemiological studies reviewed. Similarly, a majority of
the studies reviewed by @fortmann2013 did not find a preventive effect
of MVMM supplementation on cancer incidence in healthy populations.

Yoga is a practice rooted in India that combines physical postures,
breathing techniques, and meditation to promote physical and mental
well-being. Yoga's effectiveness in promoting health has been examined
for several health outcomes, including headaches, pain, brain structure,
and mental health. @anheyer2020 conducted a meta-analysis of randomized
controlled trials investigating the effects of yoga in patients with a
diagnosis of chronic or episodic headache
(e.g. tension-type headache or migraine) compared to usual care and
active treatments. Results showed that yoga is associated with a
reduction in headache frequency, mainly due to effects among patients
with tension-type headaches. Among patients with migraines there was no
significant effect. The authors conclude that yoga may have short-term
efficacy in improving headache frequency, headache duration, and pain
intensity in patients suffering from tension-type headaches. @li2019
reviewed results from 10 randomized controlled trials comparing yoga to
other pain interventions among patients with chronic, nonspecific neck
pain. Results showed that yoga has a positive effect on neck pain
intensity, neck pain-related functional disability, and mood. In a
review of 11 studies on the effects of yoga on brain structure,
@gothe2019 found that yoga has a positive effect on the structure and
function of the hippocampus, amygdala, prefrontal cortex, cingulate
cortex, and brain networks including the default mode network. The
authors conclude that yoga may be a promising intervention for
mitigating age-relate and neurodegenerative declines. @vollbehr2018
conducted a meta-analysis of 18 studies studying the effect of yoga on
patients experiencing acute and chronic depression. Yoga did not have a
significant effect over usual care or active control groups, though yoga
did result in a significant reduction in depression symptoms compared to
psychoeducation control groups. The authors did not find a significant
effect on anxiety for yoga compared to active control groups. Another
systematic review by @cramer2013 of 12 randomized controlled trials with
619 participants with depressive disorders and elevated levels of
depression found moderate evidence for short-term effects of yoga
compared to usual care and limited evidence for yoga's effectiveness
compared to relaxation techniques and aerobic exercise. The authors also
found yoga to be somewhat effective in reducing anxiety symptoms.
@wang2020 performed a systematic review of 12 articles on the effects of
yoga or yoga-related interventions on stress management and remission in
healthy adults. The authors found that most types of yoga had a positive
effect on stress reduction in healthy populations. In a meta-analysis of
17 randomized controlled trials. @hendriks2017 found that yoga is
associated with a significant increase in psychological well-being
compared to no intervention, however yoga did not have a significant
effect on psychological well-being when compared to physical activity.

There is an abundance of evidence for the positive effect of exercise on
health. Physical inactivity is associated with an increased risk of
chronic disease [@anderson2019] including cancer [@magnusson1998] and
diabetes [@uusitupa2000]. Physical activity has been found to reduce
risk of declining health in overweight and obese populations independent
of weight reduction [@he2004]. In combination with adherence to a
Mediterranean diet, moderate alcohol use, and non-smoking, physical
activity is associated with a 50% lower rate of all-cause and
cause-specific mortality [@knoops2004]. In patients with type 2
diabetes, physical activity has been found to decrease systolic blood
pressure, in turn reducing the risk for diabetes-related complications,
diabetes-related death, and myocardial infarction [@adler2000]. Among
cancer patients, physical activity is related to better health-related
quality of life [@calle2002] and reduced risk and disease burden
conveyed by co-morbid conditions [@penedo2004]. Physical activity is
associated with a reduced risk of adverse cardiovascular events
[@wessel2004; @blumenthal2004]. Consistent physical activity has been
shown to prevent the onset of depression [@paffenbargerjr1994] and to
reduce depression and anxiety symptoms [@ross1988; @stephens1988;
@babyak2000].

Eating habits are another health behavior known to impact health. There
are a plethora of dietary patterns and popular diets observed in the
general population. Generally, dietary patterns characterized by fruit,
vegetable, whole grain, fish, and poultry consumption tend to be related
to increased micronutrient intake and lower disease risk [@kant2004].
More healthful diets are inversely related to all-cause mortality and
cardiovascular disease risk, though a systematic review of dietary
studies notes that risk reduction is modest and tends to be attenuated
when controls are introduced [@kant2004]. Low salt diets are associated
with a reduction in death from cardiovascular disease, and tends to be
recommended for heart failure and chronic kidney disease
[@suckling2015]. Over the last couple decades, many different diets have
gained popularity. The effectiveness of any given popular diet is
something necessary of further study, however in a randomized controlled
trial of overweight and obese adults comparing four popular diets
(Atkins, Zone, Weight Watchers, and Ornish) found that diet adherence
was a better predictor of weight loss and reduction of cardiac risk
factors than the type of diet used [@dansinger2005]. Plant-based and
vegetarian diets have been associated with reduced risk of negative
health outcomes, including lower cholesterol, diabetes, heart disease,
and cancer [@oussalah2020; @mcevoy2012].

## Manipulative Treatments

Manipulative treatments are treatments in which practitioners physically
manipulate the systems and structures of the body, such as bones,
joints, and soft tissues, to improve physical ailments. Manipulative
treatments are based on the belief that the systems and structures of
the body are dependent on each other and self-regulating. This
dissertation examines the use of two manipulative treatments: massage
and chiropractic care.

Massage has been examined as a possible treatment for a variety of pain
conditions. @crawford2016 conducted a meta-analysis of massage
effectiveness in treating pain in pain populations. Results show that
massage is more effective in treating pain compared to sham controls, no
treatment, and active controls (e.g. joint manipulation, physical
therapy, acupuncture). Among patients with fibromyalgia, massage has
been shown to significantly improve pain after 5 weeks of treatment
[@li2014]. Massage has been found to relieve pain in the short term in
patients with low back pain [@furlan2015; @kumar2013]. A meta-analysis
of 12 randomized controlled trials on the effectiveness of massage
therapy in treating neck and shoulder found that massage therapy is
effective in treating both neck and should pain compared to inactive
therapy [@kong2013]. Compared to active therapies, massage showed short
effects for relieving shoulder pain but not neck pain. In patients
headaches, massage is associated with a greater reduction in headache
pain compared to a placebo [@moraska2015] and a reduction in migraine
frequency [@happe2016]. Massage therapy has similarly been associated
with improvement in depression and anxiety symptoms [@hou2010; @li2014;
@crawford2016], showing similar effectiveness to psychotherapy in
meta-analyses [@moyer2004].

Chiropractic care has been examined as a possible treatment for several
health outcomes. @salehi2015 reviewed 11 systematic reviews that were
specifically concerned with chiropractic care effectiveness and included
evidence from clinical trials focused on as specific disease. Results
showed that chiropractic care may effectively improve neck pain,
shoulder and neck trigger points, and sports injuries. The authors found
no conclusive evidence for chiropractic care's effectiveness in treating
asthma, infant colic, autism spectrum disorder, gastrointestinal
problems, fibromyalgia, back pain, carpal tunnel syndrome.

For most CAMs, there is little to no evidence of clinical effectiveness, though this has been shown to vary by intended use. For example, in a systematic review of CAM studies, Ernst (2000) found convincing evidence that acupuncture relieves nausea but no convincing evidence that acupuncture relieves chronic pain. Ernst also found that herbal supplements such as St. John’s wort for depression and Ginkgo biloba for intermittent claudication (i.e. muscle pain with mild exertion) were both more effective than placebos. Ernst found no convincing clinical evidence for the effectiveness of chelation therapy, homeopathy, massage, reflexology, or spiritual healing for treating a variety of ailments. In a review of studies on the efficacy of CAM use for treating chronic pain, Tan et al. (2007) also found mixed evidence for CAMs as a group, though efficacy varied across the CAM domains. Tan et al. (2007) found biologically based medicine, some forms of energy medicine, mind-body medicine, and manipulative body-based medicine to range from possibly efficacious to evidently efficacious. Only hypnosis was found to be evidently efficacious and specific for treating chronic pain. Reiki, a form of energy healing, was not efficacious in treating chronic pain.  

# Motivations for CAM Use

If the efficacy of CAMs is questionable at best, what motivates their use? A range of motivations have been considered by previous literature, including perceptions of effectiveness and safety, congruence with spiritual philosophy and health beliefs, a sense of control over one's health, dissatisfaction with conventional medicine, and treatment of specific conditions, particularly chronic pain (Barnes et al. 2008; Ernst 2000; Greene et al. 2009; Sirois and Gick 2002). Whereas the effectiveness of CAMs has not been well-supported in clinical trials, CAM users report both physical and psychological health benefits, such as improved physical functioning, relief of negative physical symptoms, improved coping and resilience, and decreased symptoms of depression and anxiety (Greene et al. 2009). Perceived effectiveness of CAMs among users appears to be amplified by a motivation toward general health and wellness. Drawing on 2012 National Health Interview Survey data, Rhee, Westberg, and Harris (2018) found that compared to individuals who use CAMs for treatment only, individuals who utilize CAMs for general wellness in addition to the treatment of specific conditions report a better sense of control over their health and improved overall health. This may indicate that CAM use has particularly positive perceived benefits for those who are consciously motivated toward general health and well-being.

# Theoretical Perspectives on Health Lifestyles and Socioeconomic Status

In this section, I will discuss theoretical perspectives on health lifestyles and socioeconomic status. I will first discuss two general theories of stratification and health. Then, I will discuss theoretical perspectives relevant to the components of socioeconomic status. All theories point to similar conclusions, namely that higher socioeconomic status is associated with resources that can be leveraged to gain better health. 

## Fundamental Causes

In response to epidemiology's focus on proximate, individual-level risk
factors, Bruce Link and Jo Phelan (1995) developed the theory of
fundamental causes to draw attention to social conditions as the root
cause of health disparities. Link and Phelan observe that the
association between socioeconomic status and health has persisted across
changing historical contexts involving extraordinary advancements in
public health, advancements which were fully expected to eradicate
socioeconomic health disparities (e.g. mass immunization and public
sanitation improvements). Why has this association endured? Link and
Phelan posit that SES is a fundamental cause of health due to the
multiplicity of mechanisms by which it impacts health. As some diseases
are eradicated, new ones take their place. As risk factors, and
therefore the mechanisms that had produced the association between SES
and health from the mid-20th century, disappeared, new risk factors took
their place. As risk factors and mechanisms changed, individuals with
higher SES were better situated to leverage their resources (e.g.
knowledge, money, power, prestige, and social connections) toward
protective behaviors and environments that favor better health. Thus,
the association between SES and health is not attributable to any one
set of mechanisms, but to the flexibility with which socioeconomic
resources may be employed in pursuit of better health (Link et al. 2008;
Lutfey and Freese 2005).

## Health Lifestyle Theory

William Cockerham and colleagues (Cockerham 1997, 2005, 2007; William C.
Cockerham 2013; William C Cockerham 2013; Cockerham, Abel, and Lüschen
1993; Cockerham, Snead, and DeWaal 2002) developed Health Lifestyle
Theory by synthesizing, among other works, Max Weber's Economy and
Society (1978) and Pierre Bourdieu' Distinction (1984). Cockerham (1997,
p. 321) defines health lifestyles as "collective patterns of
health-related behavior based on choices from options available to
people according to their life chances." His precise theoretical model
can be divided into two primary components: structural influences and
the habitus.

Weber (1978)contribution to the structural component of health lifestyle theory begins with his assertion that lifestyles are formed in status groups. Status groups are aggregates of people with similar status and class backgrounds whose association features a sharing of similar lifestyles. Social statuses or structural locations within systems of stratification direct our exposure to specific elements of culture like health-related beliefs, norms, and customs through socialization and experience. The idea is that people with common social backgrounds will subscribe to the same elements of culture because they tend to have similar socialization experiences. The most powerful structural variable involved in this process is class circumstances, along with age, race, gender, and the influence of collectivities (e.g., family, work, and religion) and living conditions. Common socialization experiences and common elements of culture within the context of these structural variables (what Bourdieu calls "fields") eventually shape our life choices (agency). At the same time, our social positions also drive our life chances (structure) by regulating our access to resources through basic social stratification processes. People have lifestyle choices, but those choices are constrained by what is available to them given their social position. The final feature of the structural component is the dialectical interplay of agency (choices) and structure (chances). Cockerham (2005, p.61) explains that people "align their goals, needs, and desires with their probabilities for realizing them and choose a lifestyle according to their assessments of the reality of their resources and class circumstances."

The repetitive interplay of choices (agency) and chances (structure) through socialization and experience leads to the development of habitus or internalized dispositions toward behavior or action. The modern concept of the habitus was refined by Bourdieu (1984)and represents perhaps his most lasting contribution to sociological theory. According to Cockerham (2005, p. 61), “the habitus serves as a cognitive map or set of perceptions that routinely guides and evaluates a person’s choices and options. It provides enduring dispositions toward acting deemed appropriate by a person in particular social situations and settings.” Once the habitus is formed, health-related practices like smoking, exercise, and dietary behavior become “integrated into routine behavioral repertories that can be acted out more or less unthinkingly” (Cockerham, 2005, p. 62). The final element of the habitus component is the reproduction of health lifestyles through feedback processes. When health lifestyles are formed and enacted, “they tend to reproduce or modify the habitus from which they are derived” (Cockerham, 2005, p. 63). In other words, when we carry out our lifestyles, we either reinforce or alter our dispositions and practices. 

## Human Capital Theory

John Mirowsky and Catherine Ross (1998, 2003) developed their Human
Capital Theory by synthesizing the works of Gary Becker (1964)in
economics and Julian Rotter (1966) in psychology. In contrast to
Cockerham's General Theory (which can be applied to any system of
stratification), Mirowsky and Ross' theory is focused exclusively on
explaining how healthy lifestyles flow from years of formal education.
Mirowsky and Ross' theoretical model can be divided into two primary
components: the human capital component and the learned-effectiveness
component.

The first component, drawing primarily from Becker (1964), argues that “formal education indicates investment in ‘human capital’ - the productive capacity developed, embodied, and stocked in human beings themselves” (Mirowsky & Ross, 2003, p. 51). The idea is relatively straightforward: The process of formal education nurtures knowledge, skills, and abilities that help people to solve problems and to be productive in their own lives. Some of the more important elements of education include health-related knowledge and skills associated with reading, writing, researching, critical thinking, and communicating.

The second component, drawing primarily from Rotter (1966), argues that formal educational attainment, human capital investment, and the development of skills and abilities tends to foster a healthy lifestyle by promoting a general sense of learned-effectiveness or personal control over one’s life. According to Mirowsky and Ross (2003, p. 64), “education raises the sense of personal control because it helps people successfully prevent problems, or solve them if prevention fails, to achieve their goals, and shape their own lives.” Through years of formal education, skill development, and structured problem solving, people learn that they can organize their lives, achieve goals, and actively manage the good and bad things that happen to them. The sense of control then contributes to a healthy lifestyle by cultivating a proactive or agentic orientation toward one’s health. Mirowsky and Ross (2003, p. 66) explain that “people with a sense of personal control know more about health, they are more likely to initiate preventive behaviors like quitting smoking, exercising, or maintaining a normal weight.” 

## Health Commodity Theory

The Health Commodity Theory was initially described by Ross and Mirowsky
(2000) in the context of explaining the link between socioeconomic
status (SES) and health. A commodity is something of value that can be
bought and sold. Health commodity theory argues that SES promotes health
through purchasing power. Similar to fundamental social causes theory
(Link & Phelan, 2000), health commodity theory is structural and
materialistic. That is, health commodity theory tends to reduce the
complex association between SES and health to mechanisms linked to
financial resources or things people can buy like health care,
pharmaceuticals, and healthier foods. Ultimately, the defining question
is "who gets what?" (Link & Phelan, 2000).

Health Lifestyle Theory and Human Capital Theory take the same general form. Both theories argue that social structure shapes and clusters health related behavior through social psychological processes. While Cockerham emphasizes the mechanisms of socialization and habitus (internalized behavior norms), Mirowsky and Ross stress the development of human capital (skills and abilities) and the sense of personal control (beliefs about one’s personal effectiveness). Health commodity theory competes with these social psychological theories by emphasizing a direct link between social structure and health- related behavior. Although health lifestyle theory and human capital theory acknowledge the role of resource stratification in explaining broader structural disparities in health lifestyles, they also recognize more elaborate downstream social psychological processes. If the predictions of health commodity theory are correct, educational variations in health lifestyles should be partially mediated or explained by income. Under these conditions, the effects of education on health-related behavior would be partially due to the fact that people with higher levels of education tend to earn more money. This reality would minimize (not eliminate) the explanatory power of processes related to socialization and habitus, human capital, and the sense of personal control. 

# Contributions

This dissertation will advance the literature on health lifestyles in several ways. First, to this point in time, studies on health lifestyles have not included CAMs, which are utilized by a substantial portion of the US population. Second, most studies on CAM use have utilized cross-sectional or trend data. This study will utilize longitudinal data across three time points. This will allow me to examine when CAM use changes for individuals over time, how CAM use changes, and for whom those changes occur with respect to health. Additionally, this longitudinal design will allow me to establish health lifestyles as a mechanism for the relationship between SES and health. Third, to my knowledge, no studies on CAM use have examined the relationship between occupation and CAM use, or the relationship between CAM use and a comprehensive measure of socioeconomic status. I will investigate associations between CAM use and a comprehensive measure of socioeconomic status as well as the individual components of socioeconomic status (income, education, and occupation). Finally, I will compare the social patterning of traditional health lifestyles (THLs) to that of alternative health lifestyles (AHLs), and their roles in producing health.
