---
title: "descriptive and bivariate results education"
author: "Hannah Andrews"
date: "11/17/2021"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidycomm)
library(haven)
library(tidyverse)
library(foreach)
library(kableExtra)
library(janitor)
library(stargazer)
library(tables)
```

```{r, echo = FALSE, results='hide'}
# Set working directory 
setwd("C:/Users/hanna/Documents/git/AHL/R")
# Read in stata file for MIDUS 1
path <- ("C:/Users/hanna/Documents/git/AHL/Stata/data-cleaning/MIDUS1.dta")
M1 <- read_dta(path)
a.lta.var.list <- c("M2ID", "acam1", "acam2", "acam3", "acam4", "acam5", "acam6", "acam7", 
               "acam8", "acam9", "acam10", "acam11", "acam12", "acam13", "acam14", "acam15",
               "acam21", "AEduc", "ARace", "ASex", "lnAHhInc", "aMarried", "aHlthIns", "AAge", 
               "A1SCHROX", "A1SCHRON", "A1PA4")

a.cams.lta <- M1[a.lta.var.list] # Subset MIDUS1 - only include CAMs.
# Create column that is the sum of CAMs used 
a.cams.lta$totalCams <- rowSums(a.cams.lta[, c(2:12, 14, 15, 17)])

# Rename columns 
a.cams.lta <- dplyr::rename(a.cams.lta, 
                            Acupuncture_W1 = acam1, 
                            Biofeedback_W1 = acam2,
                            Chiropractic_W1 = acam3,
                            EnergyHeal_W1 = acam4,
                            ExerciseMove_W1 = acam5,
                            Herbal_W1 = acam6,
                            Vitamins_W1 = acam7,
                            Homeopathy_W1 = acam8,
                            Hypnosis_W1 = acam9,
                            ImageryTech_W1 = acam10,
                            Massage_W1 = acam11,
                            Prayer_W1 = acam12,
                            RelaxMeditate_W1 = acam13,
                            SpecialDiet_W1 = acam14, 
                            SpiritHeal_W1 = acam15, 
                            PraySpirit_W1 = acam21,
                            Education_W1 = AEduc,
                            Race_W1 = ARace,
                            Sex_W1 = ASex,
                            LogIncome_W1 = lnAHhInc,
                            Marital_W1 = aMarried,
                            HlthInsurance_W1 = aHlthIns,
                            Age_W1 = AAge,
                            SumChron_W1 = A1SCHROX, 
                            totalCams_W1 = totalCams, 
                            SRHealth_W1 = A1PA4)
head(a.cams.lta)

# Convert education to factor 
a.cams.lta$Education_W1 <- as_factor(a.cams.lta$Education_W1, levels = "labels")
# Convert Race to factor
a.cams.lta$Race_W1 <- as_factor(a.cams.lta$Race_W1, levels = "labels")
# Convert Sex to factor
a.cams.lta$Sex_W1 <- as_factor(a.cams.lta$Sex_W1, levels = "labels")
# Convert marital to factor
a.cams.lta$Marital_W1 <- as_factor(a.cams.lta$Marital_W1, levels = "labels")
# Convert Health insurance to factor
a.cams.lta$HlthInsurance_W1 <- as_factor(a.cams.lta$HlthInsurance_W1, levels = "labels")
# Convert Age to numeric 
a.cams.lta$Age_W1 <- as.numeric(a.cams.lta$Age_W1)

# Save as wave1data.rda
wave1 <- a.cams.lta
save(wave1, file = "C:/Users/hanna/Documents/git/AHL/R/wave1data.rda")

# Wave 2
# Prayer and spiritual healing combined in stata.

# Read in MIDUS2 data and subset to complete cases on CAMs
# Read in stata file for MIDUS 2
path <- ("C:/Users/hanna/Documents/git/AHL/Stata/data-cleaning/MIDUS2.dta")
M2 <- read_dta(path)
b.cams.list <- c("M2ID", "bcam1", "bcam2", "bcam3", "bcam4", "bcam5", "bcam6", "bcam7", 
               "bcam8", "bcam9", "bcam10", "bcam11", "bcam12", "bcam13", "bcam14", "bcam15", 
               "bcam21", "bAge", "lnbHhInc", "bEduc", "bRace", "bSex", "bHlthIns", "bMarried",
               "B1SCHROX", "B1SCHRON", "B1PA1")

b.cams.lta <- M2[b.cams.list] # Subset MIDUS2 - only include CAMs.

# Create column that is the sum of CAMs used 
b.cams.lta$totalCams <- rowSums(b.cams.lta[, c(2:12, 14, 15, 17)])

# Rename columns 
b.cams.lta <- dplyr::rename(b.cams.lta, 
                            Acupuncture_W2 = bcam1, 
                            Biofeedback_W2 = bcam2,
                            Chiropractic_W2 = bcam3,
                            EnergyHeal_W2 = bcam4,
                            ExerciseMove_W2 = bcam5,
                            Herbal_W2 = bcam6,
                            Vitamins_W2 = bcam7,
                            Homeopathy_W2 = bcam8,
                            Hypnosis_W2 = bcam9,
                            ImageryTech_W2 = bcam10,
                            Massage_W2 = bcam11,
                            Prayer_W2 = bcam12,
                            RelaxMeditate_W2 = bcam13,
                            SpecialDiet_W2 = bcam14, 
                            SpiritHeal_W2 = bcam15, 
                            PraySpirit_W2 = bcam21,
                            Age_W2 = bAge,
                            LogIncome_W2 = lnbHhInc,
                            Education_W2 = bEduc,
                            Race_W2 = bRace,
                            Sex_W2 = bSex,
                            HlthInsurance_W2 = bHlthIns,
                            Marital_W2 = bMarried, 
                            SumChron_W2 = B1SCHROX, 
                            totalCams_W2 = totalCams, 
                            SRHealth_W2 =  B1PA1)
head(b.cams.lta)

# Convert age to numeric
b.cams.lta$Age_W2 <- as.numeric(b.cams.lta$Age_W2)
# Convert education to factor 
b.cams.lta$Education_W2 <- haven::as_factor(b.cams.lta$Education_W2, levels = "labels")
# Convert Race to factor 
b.cams.lta$Race_W2 <- haven::as_factor(b.cams.lta$Race_W2, levels = "labels")
# Convert sex to factor 
b.cams.lta$Sex_W2 <- haven::as_factor(b.cams.lta$Sex_W2, levels = "labels")
# Convert marital status to factor 
b.cams.lta$Marital_W2 <- haven::as_factor(b.cams.lta$Marital_W2, levels = "labels")
# Convert health insurance to factor
b.cams.lta$HlthInsurance_W2 <- haven::as_factor(b.cams.lta$HlthInsurance_W2, levels = "labels")

wave2 <- b.cams.lta
save(wave2, file = "C:/Users/hanna/Documents/git/AHL/R/wave2data.rda")

# Wave 3
# This chunk reads in the MIDUS2 Stata .dta file, subsets the data to only include CAMs, and restricts the data to complete cases. 

# Prayer and spiritual healing combined in stata.

# Read in MIDUS2 data and subset to complete cases on CAMs
# Read in stata file for MIDUS 2
path <- ("C:/Users/hanna/Documents/git/AHL/Stata/data-cleaning/MIDUS3.dta")
M3 <- read_dta(path)
c.cams.list <- c("M2ID", "ccam1", "ccam2", "ccam3", "ccam4", "ccam5", "ccam6", "ccam7", 
               "ccam8", "ccam9", "ccam10", "ccam11", "ccam12", "ccam13", "ccam14", 
               "ccam15", "ccam21", "C1STATUS", "CAge", "lnCHhInc", "CEduc", "CRace", 
               "CSex", "cMarried", "cHlthIns", "C1SCHROX", "C1SCHRON", "C1PA1")

c.cams.lta <- M3[c.cams.list] # Subset MIDUS2 - only include CAMs.

# Create column that is the sum of CAMs used 
c.cams.lta$totalCams <- rowSums(c.cams.lta[, c(2:12, 14, 15, 17)])

# Rename columns 
c.cams.lta <- dplyr::rename(c.cams.lta, 
                            Acupuncture_W3 = ccam1, 
                            Biofeedback_W3 = ccam2,
                            Chiropractic_W3 = ccam3,
                            EnergyHeal_W3 = ccam4,
                            ExerciseMove_W3 = ccam5,
                            Herbal_W3 = ccam6,
                            Vitamins_W3 = ccam7,
                            Homeopathy_W3 = ccam8,
                            Hypnosis_W3 = ccam9,
                            ImageryTech_W3 = ccam10,
                            Massage_W3 = ccam11,
                            Prayer_W3 = ccam12,
                            RelaxMeditate_W3 = ccam13,
                            SpecialDiet_W3 = ccam14, 
                            SpiritHeal_W3 = ccam15, 
                            PraySpirit_W3 = ccam21,
                            Age_W3 = CAge,
                            LogIncome_W3 = lnCHhInc,
                            Education_W3 = CEduc,
                            Race_W3 = CRace,
                            Sex_W3 = CSex,
                            Marital_W3 = cMarried,
                            HlthInsurance_W3 = cHlthIns, 
                            SumChron_W3 = C1SCHROX, 
                            totalCams_W3 = totalCams, 
                            SRHealth_W3 = C1PA1)
head(c.cams.lta)

# Age and income already set as numeric 
# Convert education to factor 
c.cams.lta$Education_W3 <- haven::as_factor(c.cams.lta$Education_W3, levels = "labels")
# Convert race to factor
c.cams.lta$Race_W3 <- haven::as_factor(c.cams.lta$Race_W3, levels = "labels")
# Convert sex to factor 
c.cams.lta$Sex_W3 <- haven::as_factor(c.cams.lta$Sex_W3, levels = "labels")
# Convert marital to factor 
c.cams.lta$Marital_W3 <- haven::as_factor(c.cams.lta$Marital_W3, levels = "labels")
# Convert health insurance to factor 
c.cams.lta$HlthInsurance_W3 <- haven::as_factor(c.cams.lta$HlthInsurance_W3, levels = "labels")

wave3 <- c.cams.lta

save(wave3, file = "C:/Users/hanna/Documents/git/AHL/R/wave3data.rda")

# Set working directory 
setwd("C:/Users/hanna/Documents/git/AHL/R/descriptive and bivariate results")

```
```{r, echo = FALSE}
# This code chunk creates the factor dummy indices 
# Factor 1: Mind body practices 
# wave 1
wave1$mindbody <- rowSums(wave1[, c("PraySpirit_W1", "EnergyHeal_W1", "ImageryTech_W1",
                                    "RelaxMeditate_W1", "Hypnosis_W1")])
# wave 2
wave2$mindbody <- rowSums(wave2[, c("PraySpirit_W2", "EnergyHeal_W2", "ImageryTech_W2",
                                    "RelaxMeditate_W2", "Hypnosis_W2")])
#wave 3
wave3$mindbody <- rowSums(wave3[, c("PraySpirit_W3", "EnergyHeal_W3", "ImageryTech_W3",
                                    "RelaxMeditate_W3", "Hypnosis_W3")])

# Factor 2: Alternative medical systems
# wave 1
wave1$altmed <- rowSums(wave1[, c("Homeopathy_W1", "Herbal_W1", "Acupuncture_W1")])
# wave 2
wave2$altmed <- rowSums(wave2[, c("Homeopathy_W2", "Herbal_W2", "Acupuncture_W2")])
# wave 3
wave3$altmed <- rowSums(wave3[, c("Homeopathy_W3", "Herbal_W3", "Acupuncture_W3")])

# Factor 3: Physical and Nutritional Approaches
wave1$pna <- rowSums(wave1[, c("Vitamins_W1", "ExerciseMove_W1", "SpecialDiet_W1")])
wave2$pna <- rowSums(wave2[, c("Vitamins_W2", "ExerciseMove_W2", "SpecialDiet_W2")])
wave3$pna <- rowSums(wave3[, c("Vitamins_W3", "ExerciseMove_W3", "SpecialDiet_W3")])

# Factor 4: Manipulative treatments
wave1$manipulative <- rowSums(wave1[, c("Massage_W1", "Chiropractic_W1")])
wave2$manipulative <- rowSums(wave2[, c("Massage_W2", "Chiropractic_W2")])
wave3$manipulative <- rowSums(wave3[, c("Massage_W3", "Chiropractic_W3")])
```

# Individual CAMs

## Wave 1
### Crosstabs
```{r, echo = FALSE}
# Create crosstabs education and all cams. 

varlist <- c("Acupuncture_W1", "Biofeedback_W1", "Chiropractic_W1", "EnergyHeal_W1", "ExerciseMove_W1", "Herbal_W1", "Homeopathy_W1", "Hypnosis_W1", "ImageryTech_W1", "Massage_W1", "PraySpirit_W1", "RelaxMeditate_W1", "SpecialDiet_W1", "Vitamins_W1")

for(j in varlist){
  tbl <- wave1 %>% 
    tabyl(Education_W1, .data[[j]]) %>% 
    adorn_percentages("row") %>%
    adorn_pct_formatting(digits = 2) %>% 
    adorn_ns() %>% 
    adorn_title("combined") %>% 
    knitr::kable()
  print(tbl)
}
```

### Chi squares
```{r, echo = FALSE}
# Run chi squares
# subset data for lapply; only include education and CAMs
vars <- c("Education_W1", "Acupuncture_W1", "Biofeedback_W1", "Chiropractic_W1", "EnergyHeal_W1", "ExerciseMove_W1", "Herbal_W1", "Homeopathy_W1", "Hypnosis_W1", "ImageryTech_W1", "Massage_W1", "PraySpirit_W1", "RelaxMeditate_W1", "SpecialDiet_W1", "Vitamins_W1")
wave1.educ.df <- wave1[vars]

educ.cams.chisquares <- lapply(wave1.educ.df[-length(wave1.educ.df)], function(x) chisq.test(table(wave1$Education_W1, x)))
educ.cams.chisquares

```

## Wave 2
### Crosstabs 
```{r, echo = FALSE}
varlist <- c("Acupuncture_W2", "Biofeedback_W2", "Chiropractic_W2", "EnergyHeal_W2", "ExerciseMove_W2", "Herbal_W2", "Homeopathy_W2", "Hypnosis_W2", "ImageryTech_W2", "Massage_W2", "PraySpirit_W2", "RelaxMeditate_W2", "SpecialDiet_W2", "Vitamins_W2")

for(j in varlist){
  tbl <- wave2 %>% 
    tabyl(Education_W2, .data[[j]]) %>% 
    adorn_percentages("row") %>%
    adorn_pct_formatting(digits = 2) %>% 
    adorn_ns() %>% 
    adorn_title("combined") %>% 
    knitr::kable()
  print(tbl)
}
```

### Chi squares 
```{r, echo = FALSE}
# Run chi squares
# subset data for lapply; only include education and CAMs
vars <- c("Education_W2", "Acupuncture_W2", "Biofeedback_W2", "Chiropractic_W2", "EnergyHeal_W2", "ExerciseMove_W2", "Herbal_W2", "Homeopathy_W2", "Hypnosis_W2", "ImageryTech_W2", "Massage_W2", "PraySpirit_W2", "RelaxMeditate_W2", "SpecialDiet_W2", "Vitamins_W2")
wave2.educ.df <- wave2[vars]

educ.cams.chisquares <- lapply(wave2.educ.df[-length(wave2.educ.df)], function(x) chisq.test(table(wave2$Education_W2, x)))
educ.cams.chisquares
```

## Wave 3 

### Crosstabs 
```{r, echo = FALSE}
varlist <- c("Acupuncture_W3", "Biofeedback_W3", "Chiropractic_W3", "EnergyHeal_W3", "ExerciseMove_W3", "Herbal_W3", "Homeopathy_W3", "Hypnosis_W3", "ImageryTech_W3", "Massage_W3", "PraySpirit_W3", "RelaxMeditate_W3", "SpecialDiet_W3", "Vitamins_W3")

for(j in varlist){
  tbl <- wave3 %>% 
    tabyl(Education_W3, .data[[j]]) %>% 
    adorn_percentages("row") %>%
    adorn_pct_formatting(digits = 2) %>% 
    adorn_ns() %>% 
    adorn_title("combined") %>% 
    knitr::kable()
  print(tbl)
}
```

### Chi squares 
```{r, echo = FALSE}
# Run chi squares
# subset data for lapply; only include education and CAMs
vars <- c("Education_W3", "Acupuncture_W3", "Biofeedback_W3", "Chiropractic_W3", "EnergyHeal_W3", "ExerciseMove_W3", "Herbal_W3", "Homeopathy_W3", "Hypnosis_W3", "ImageryTech_W3", "Massage_W3", "PraySpirit_W3", "RelaxMeditate_W3", "SpecialDiet_W3", "Vitamins_W3")
wave3.educ.df <- wave3[vars]

educ.cams.chisquares <- lapply(wave3.educ.df[-length(wave3.educ.df)], function(x) chisq.test(table(wave3$Education_W3, x)))
educ.cams.chisquares
```

# Dummy Count 

## Wave 1
```{r, echo = FALSE}
# Crosstab
  tbl <- wave1 %>% 
    tabyl(Education_W1, totalCams_W1) %>% 
    adorn_percentages("row") %>%
    adorn_pct_formatting(digits = 2) %>% 
    adorn_ns() %>% 
    adorn_title("combined") %>% 
    knitr::kable()
  print(tbl)

# Summary statistics 
library(dplyr)
group_by(wave1, Education_W1) %>%
  summarise(
    count = n(),
    mean = mean(totalCams_W1, na.rm = TRUE),
    sd = sd(totalCams_W1, na.rm = TRUE)
  )

# Visualize data
library(ggpubr)
ggboxplot(wave1, x = "Education_W1", y = "totalCams_W1",
          color = "Education_W1", palette = c("#00AFBB", "#E7B800", "#FC4E07", "#3369FF", "#F633FF"),
          ylab = "Total Cams", xlab = "Education")

# Visualize means by group
ggline(wave1, x = "Education_W1", y = "totalCams_W1", 
       add = c("mean_se"),
       ylab = "Total Cams", xlab = "Education")

# Levene's test 
library(car)
result <- leveneTest(totalCams_W1 ~ Education_W1, wave1)
result
# Significant so can't use one way ANOVA. 

# Kruskal wallis test
kruskal.test(totalCams_W1 ~ Education_W1, data = wave1)
# p less than .05 meaning there are significant differences in the means between groups 
```

## Wave 2
```{r, echo = FALSE}
# Crosstab
  tbl <- wave2 %>% 
    tabyl(Education_W2, totalCams_W2) %>% 
    adorn_percentages("row") %>%
    adorn_pct_formatting(digits = 2) %>% 
    adorn_ns() %>% 
    adorn_title("combined") %>% 
    knitr::kable()
  print(tbl)

# Summary statistics 
library(dplyr)
group_by(wave2, Education_W2) %>%
  summarise(
    count = n(),
    mean = mean(totalCams_W2, na.rm = TRUE),
    sd = sd(totalCams_W2, na.rm = TRUE)
  )

# Visualize data
library(ggpubr)
ggboxplot(wave2, x = "Education_W2", y = "totalCams_W2",
          color = "Education_W2", palette = c("#00AFBB", "#E7B800", "#FC4E07", "#3369FF", "#F633FF"),
          ylab = "Total Cams", xlab = "Education")

# Visualize means by group
ggline(wave2, x = "Education_W2", y = "totalCams_W2", 
       add = c("mean_se"),
       ylab = "Total Cams", xlab = "Education")

# Levene's test 
library(car)
result <- leveneTest(totalCams_W2 ~ Education_W2, wave2)
result
# Significant so can't use one way ANOVA. 

# Kruskal wallis test
kruskal.test(totalCams_W2 ~ Education_W2, data = wave2)
# p less than .05 meaning there are significant differences in the means between groups 
```
## Wave 3
```{r, echo = FALSE}
# Crosstab
  tbl <- wave3 %>% 
    tabyl(Education_W3, totalCams_W3) %>% 
    adorn_percentages("row") %>%
    adorn_pct_formatting(digits = 3) %>% 
    adorn_ns() %>% 
    adorn_title("combined") %>% 
    knitr::kable()
  print(tbl)

# Summary statistics 
library(dplyr)
group_by(wave3, Education_W3) %>%
  summarise(
    count = n(),
    mean = mean(totalCams_W3, na.rm = TRUE),
    sd = sd(totalCams_W3, na.rm = TRUE)
  )

# Visualize data
library(ggpubr)
ggboxplot(wave3, x = "Education_W3", y = "totalCams_W3",
          color = "Education_W3", palette = c("#00AFBB", "#E7B800", "#FC4E07", "#3369FF", "#F633FF"),
          ylab = "Total Cams", xlab = "Education")

# Visualize means by group
ggline(wave3, x = "Education_W3", y = "totalCams_W3", 
       add = c("mean_se"),
       ylab = "Total Cams", xlab = "Education")

# Levene's test 
library(car)
result <- leveneTest(totalCams_W3 ~ Education_W3, wave3)
result
# Significant so can't use one way ANOVA. 

# Kruskal wallis test
kruskal.test(totalCams_W3 ~ Education_W3, data = wave3)
# p less than .05 meaning there are significant differences in the means between groups 
```

# Predicted classes 
Wave 1 education and the pooled lca results 4 class solution without biofeedback 

# Factor dummy indices 

## Wave 1

### crosstabs
```{r, echo = FALSE}

varlist <- c("mindbody", "pna", "altmed", "manipulative")

for(j in varlist){
  tbl <- wave1 %>% 
    tabyl(Education_W1, .data[[j]]) %>% 
    adorn_percentages("row") %>%
    adorn_pct_formatting(digits = 2) %>% 
    adorn_ns() %>% 
    adorn_title("combined") %>% 
    knitr::kable()
  print(tbl)
}

```

### Chi Squares
```{r, echo = FALSE}
vars <- c("Education_W1", "mindbody", "pna", "altmed", "manipulative")
wave1.educ.df <- wave1[vars]

educ.factors.chisquares <- lapply(wave1.educ.df[-length(wave1.educ.df)], function(x) chisq.test(table(wave1$Education_W1, x)))

educ.factors.chisquares
```

## Wave 2

### crosstabs
```{r, echo = FALSE}

varlist <- c("mindbody", "pna", "altmed", "manipulative")

for(j in varlist){
  tbl <- wave2 %>% 
    tabyl(Education_W2, .data[[j]]) %>% 
    adorn_percentages("row") %>%
    adorn_pct_formatting(digits = 2) %>% 
    adorn_ns() %>% 
    adorn_title("combined") %>% 
    knitr::kable()
  print(tbl)
}

```

### Chi Squares
```{r, echo = FALSE}
vars <- c("Education_W2", "mindbody", "pna", "altmed", "manipulative")
wave2.educ.df <- wave2[vars]

educ.factors.chisquares <- lapply(wave2.educ.df[-length(wave2.educ.df)], function(x) chisq.test(table(wave2$Education_W2, x)))

educ.factors.chisquares
```

## Wave 3

### crosstabs
```{r, echo = FALSE}

varlist <- c("mindbody", "pna", "altmed", "manipulative")

for(j in varlist){
  tbl <- wave3 %>% 
    tabyl(Education_W3, .data[[j]]) %>% 
    adorn_percentages("row") %>%
    adorn_pct_formatting(digits = 3) %>% 
    adorn_ns() %>% 
    adorn_title("combined") %>% 
    knitr::kable()
  print(tbl)
}

```

### Chi Squares
```{r, echo = FALSE}
vars <- c("Education_W3", "mindbody", "pna", "altmed", "manipulative")
wave3.educ.df <- wave3[vars]

educ.factors.chisquares <- lapply(wave3.educ.df[-length(wave3.educ.df)], function(x) chisq.test(table(wave3$Education_W3, x)))

educ.factors.chisquares
```