---
title: "Appendix C"
output:
  pdf_document: default
  bookdown::pdf_document2: default
header-includes:
- \usepackage{float}
- \usepackage{sectsty}
- \usepackage{paralist}
- \usepackage{setspace}\spacing{2}
- \usepackage{fancyhdr}
- \usepackage{lastpage}
- \usepackage{dcolumn}
- \usepackage{rotating, graphicx, longtable}
- \extrafloats{200}
always_allow_html: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)

```

```{r, echo = FALSE}
library(lme4)
library(lattice)
library(sjstats)
library(jtools)
library(ROCR)
library(sjPlot)
library(performance)
library(XML)
library(kableExtra)
library(tidyverse)
library(caTools)
library(fastDummies)
library(semptools)
library(semoutput)
library(lavaan)
library(semPlot)
library(stargazer)
library(semTable)
library(rstatix)
library(gtsummary)
library(forcats)
setwd("C:/Users/hanna/Documents/git/AHL/R/")
load("waves123.long.rda")
load("waves123.long.complete.rda")
load("waves123.wide.rda")
load("waves12.wide.complete.rda")
load("waves23.wide.complete.rda")
load("waves13.wide.complete.rda")
setwd("C:/Users/hanna/Documents/git/AHL/R/Mixed model")
# Tutorials
# https://lmudge13.github.io/sample_code/mixed_effects.html
# Converting html to pdf https://github.com/gorkang/html2latex/
```

```{r wave-comp-educ-recodes, echo=FALSE}
waves12.wide.complete$Education_W1.2 <- factor(waves12.wide.complete$Education_W1, 
                                              levels = c("College Grad", 
                                                         "Less than High School", 
                                                         "HS Diploma/GED", 
                                                         "Some College/AA Degree", 
                                                         "Graduate or Professional Degree"))


waves23.wide.complete$Education_W2.2 <- factor(waves23.wide.complete$Education_W2, 
                                              levels = c("College Grad", 
                                                         "Less than High School", 
                                                         "HS Diploma/GED", 
                                                         "Some College/AA Degree", 
                                                         "Graduate or Professional Degree"))

waves13.wide.complete$Education_W1.2 <- factor(waves13.wide.complete$Education_W1, 
                                              levels = c("College Grad", 
                                                         "Less than High School", 
                                                         "HS Diploma/GED", 
                                                         "Some College/AA Degree", 
                                                         "Graduate or Professional Degree"))

```

```{r models-waves12-chron-mod-income, echo = FALSE, results='hide'}

# Center diff chron 
waves12.wide.complete$DiffChronCenter <- scale(waves12.wide.complete$DiffChron, scale = FALSE)
waves12.wide.complete$DiffChronCenter <- as.numeric(waves12.wide.complete$DiffChronCenter)
# Center log income 
waves12.wide.complete$LogIncomeCenter <- scale(waves12.wide.complete$LogIncome_W1, scale = FALSE)
waves12.wide.complete$LogIncomeCenter <- as.numeric(waves12.wide.complete$LogIncomeCenter)
# Create interaction term 
waves12.wide.complete$DiffChronxLogIncome <- waves12.wide.complete$DiffChronCenter*waves12.wide.complete$LogIncomeCenter

# Run income model 
waves12.chron.income.1 <- lm(formula = DiffCams ~ DiffChronCenter + LogIncomeCenter, data = waves12.wide.complete)

# Run income model 
waves12.chron.income.2 <- lm(formula = DiffCams ~ DiffChronCenter + LogIncomeCenter + DiffChronCenter*LogIncomeCenter, data = waves12.wide.complete)

# Add Controls 
waves12.chron.income.3 <- lm(formula = DiffCams ~ DiffChronCenter + LogIncomeCenter + DiffChronCenter*LogIncomeCenter + Education_W1.2 + Age_W2 + Sex_W1 + Race_W2 + Marital_W2 + HlthInsurance_W2 + HLSelf_W2 + Spiritual_W2 + Religion_W2, data = waves12.wide.complete)

# Extract standard errors
waves12.chron.income.1.se <- summary(waves12.chron.income.1)$coef[,"Std. Error"]
waves12.chron.income.2.se <- summary(waves12.chron.income.2)$coef[,"Std. Error"]
waves12.chron.income.3.se <- summary(waves12.chron.income.3)$coef[,"Std. Error"]
```

```{r models-waves23-chron-mod-income, echo = FALSE, results='hide'}

# Center diff chron 
waves23.wide.complete$DiffChronCenter <- scale(waves23.wide.complete$DiffChron, scale = FALSE)
waves23.wide.complete$DiffChronCenter <- as.numeric(waves23.wide.complete$DiffChronCenter)
# Center log income 
waves23.wide.complete$LogIncomeCenter <- scale(waves23.wide.complete$LogIncome_W2, scale = FALSE)
# Create interaction term 
waves23.wide.complete$DiffChronxLogIncome <- waves23.wide.complete$DiffChronCenter*waves23.wide.complete$LogIncomeCenter

# Run income model 
waves23.chron.income.1 <- lm(formula = DiffCams ~ DiffChronCenter + LogIncomeCenter, data = waves23.wide.complete)

# Run income model 
waves23.chron.income.2 <- lm(formula = DiffCams ~ DiffChronCenter + LogIncomeCenter + DiffChronCenter*LogIncomeCenter, data = waves23.wide.complete)

# Add Controls 
waves23.chron.income.3 <- lm(formula = DiffCams ~ DiffChronCenter + LogIncomeCenter + DiffChronCenter*LogIncomeCenter + Education_W2.2 + Age_W3 + Sex_W2 + Race_W2 + Marital_W3 + HlthInsurance_W3 + HLSelf_W3 + Spiritual_W3 + Religion_W3, data = waves23.wide.complete)

# Extract standard errors
waves23.chron.income.1.se <- summary(waves23.chron.income.1)$coef[,"Std. Error"]
waves23.chron.income.2.se <- summary(waves23.chron.income.2)$coef[,"Std. Error"]
waves23.chron.income.3.se <- summary(waves23.chron.income.3)$coef[,"Std. Error"]
```

```{r models-waves13-chron-mod-income, echo = FALSE, results='hide'}

# Center diff chron 
waves13.wide.complete$DiffChronCenter <- scale(waves13.wide.complete$DiffChron, scale = FALSE)
waves13.wide.complete$DiffChronCenter <- as.numeric(waves13.wide.complete$DiffChronCenter)
# Center log income 
waves13.wide.complete$LogIncomeCenter <- scale(waves13.wide.complete$LogIncome_W1, scale = FALSE)
# Create interaction term 
waves13.wide.complete$DiffChronxLogIncome <- waves13.wide.complete$DiffChronCenter*waves13.wide.complete$LogIncomeCenter

# Run income model 
waves13.chron.income.1 <- lm(formula = DiffCams ~ DiffChronCenter + LogIncomeCenter, data = waves13.wide.complete)

# Run income model 
waves13.chron.income.2 <- lm(formula = DiffCams ~ DiffChronCenter + LogIncomeCenter + DiffChronCenter*LogIncomeCenter, data = waves13.wide.complete)

# Add Controls
waves13.chron.income.3 <- lm(formula = DiffCams ~ DiffChronCenter + LogIncomeCenter + DiffChronCenter*LogIncomeCenter + Education_W1.2 + Age_W3 + Sex_W1 + Race_W3 + Marital_W3 + HlthInsurance_W3 + HLSelf_W3 + Spiritual_W3 + Religion_W3, data = waves13.wide.complete)

waves13.chron.income.1.se <- summary(waves13.chron.income.1)$coef[,"Std. Error"]
waves13.chron.income.2.se <- summary(waves13.chron.income.2)$coef[,"Std. Error"]
waves13.chron.income.3.se <- summary(waves13.chron.income.3)$coef[,"Std. Error"]
```

```{r models-waves12-chron-mod-educ, echo = FALSE, results='hide'}

# Run income model 
waves12.chron.educ.1 <- lm(formula = DiffCams ~ DiffChronCenter + Education_W1.2, data = waves12.wide.complete)

# Run income model 
waves12.chron.educ.2 <- lm(formula = DiffCams ~ DiffChronCenter + Education_W1.2 + DiffChronCenter*Education_W1.2, data = waves12.wide.complete)

# Add Controls
waves12.chron.educ.3 <- lm(formula = DiffCams ~ DiffChronCenter + Education_W1.2 + DiffChronCenter*Education_W1.2 + LogIncome_W1 + Age_W2 + Sex_W1 + Race_W2 + Marital_W2 + HlthInsurance_W2 + HLSelf_W2 + Spiritual_W2 + Religion_W2, data = waves12.wide.complete)

# Extract standard errors
waves12.chron.educ.1.se <- summary(waves12.chron.educ.1)$coef[,"Std. Error"]
waves12.chron.educ.2.se <- summary(waves12.chron.educ.2)$coef[,"Std. Error"]
waves12.chron.educ.3.se <- summary(waves12.chron.educ.3)$coef[,"Std. Error"]
```

```{r models-waves23-chron-mod-educ, echo = FALSE, results='hide'}

# Run income model 
waves23.chron.educ.1 <- lm(formula = DiffCams ~ DiffChronCenter + Education_W2.2, data = waves23.wide.complete)

# Run income model 
waves23.chron.educ.2 <- lm(formula = DiffCams ~ DiffChronCenter + Education_W2.2 + DiffChronCenter*Education_W2.2, data = waves23.wide.complete)

# Add Controls
waves23.chron.educ.3 <- lm(formula = DiffCams ~ DiffChronCenter + Education_W2.2 + DiffChronCenter*Education_W2.2 + LogIncome_W2 + Age_W3 + Sex_W2 + Race_W2 + Marital_W3 + HlthInsurance_W3 + HLSelf_W3 + Spiritual_W3 + Religion_W3, data = waves23.wide.complete)

# Extract standard errors
waves23.chron.educ.1.se <- summary(waves23.chron.educ.1)$coef[,"Std. Error"]
waves23.chron.educ.2.se <- summary(waves23.chron.educ.2)$coef[,"Std. Error"]
waves23.chron.educ.3.se <- summary(waves23.chron.educ.3)$coef[,"Std. Error"]
```

```{r models-waves13-chron-mod-educ, echo = FALSE, results='hide'}


# Run income model 
waves13.chron.educ.1 <- lm(formula = DiffCams ~ DiffChronCenter + Education_W1.2, data = waves13.wide.complete)

# Run income model 
waves13.chron.educ.2 <- lm(formula = DiffCams ~ DiffChronCenter + Education_W1.2 + DiffChronCenter*Education_W1.2, data = waves13.wide.complete)

# Add Controls
waves13.chron.educ.3 <- lm(formula = DiffCams ~ DiffChronCenter + Education_W1.2 + DiffChronCenter*Education_W1.2 + LogIncome_W1 + Age_W3 + Sex_W1 + Race_W3 + Marital_W3 + HlthInsurance_W3 + HLSelf_W3 + Spiritual_W3 + Religion_W3, data = waves13.wide.complete)

# Extract standard errors
waves13.chron.educ.1.se <- summary(waves13.chron.educ.1)$coef[,"Std. Error"]
waves13.chron.educ.2.se <- summary(waves13.chron.educ.2)$coef[,"Std. Error"]
waves13.chron.educ.3.se <- summary(waves13.chron.educ.3)$coef[,"Std. Error"]

```

```{r model-waves12-SRH-mod-income, echo = FALSE, results='hide'}

# Center diff SRH 
waves12.wide.complete$DiffSRHCenter <- scale(waves12.wide.complete$DiffSRH, scale = FALSE)
waves12.wide.complete$DiffSRHCenter <- as.numeric(waves12.wide.complete$DiffSRHCenter)
# Create interaction term 
waves12.wide.complete$DiffSRHxLogIncome <- NA
waves12.wide.complete$DiffSRHxLogIncome <- waves12.wide.complete$DiffSRHCenter*waves12.wide.complete$LogIncomeCenter

# Run income model 
waves12.SRH.income.1 <- lm(formula = DiffCams ~ DiffSRHCenter + LogIncomeCenter, data = waves12.wide.complete)

# Run income model 
waves12.SRH.income.2 <- lm(formula = DiffCams ~ DiffSRHCenter + LogIncomeCenter + DiffSRHCenter*LogIncomeCenter, data = waves12.wide.complete)

# Add controls 
waves12.SRH.income.3 <- lm(formula = DiffCams ~ DiffSRHCenter + LogIncomeCenter + DiffSRHCenter*LogIncomeCenter + Education_W1.2 + Age_W2 + Sex_W1 + Race_W2 + Marital_W2 + HlthInsurance_W2 + HLSelf_W2 + Spiritual_W2 + Religion_W2, data = waves12.wide.complete)

# Extract standard errors
waves12.SRH.income.1.se <- summary(waves12.SRH.income.1)$coef[,"Std. Error"]
waves12.SRH.income.2.se <- summary(waves12.SRH.income.2)$coef[,"Std. Error"]
waves12.SRH.income.3.se <- summary(waves12.SRH.income.3)$coef[,"Std. Error"]

```

```{r models-waves23-SRH-mod-income, echo = FALSE, results='hide'}

# Center diff SRH 
waves23.wide.complete$DiffSRHCenter <- scale(waves23.wide.complete$DiffSRH, scale = FALSE)
waves23.wide.complete$DiffSRHCenter <- as.numeric(waves23.wide.complete$DiffSRHCenter)
# Create interaction term 
# waves23.wide.complete$DiffSRHxLogIncome <- NA
waves23.wide.complete$DiffSRHxLogIncome <- waves23.wide.complete$DiffSRHCenter*waves23.wide.complete$LogIncomeCenter


# Run income model 
waves23.SRH.income.1 <- lm(formula = DiffCams ~ DiffSRHCenter + LogIncomeCenter, data = waves23.wide.complete)

# Run income model 
waves23.SRH.income.2 <- lm(formula = DiffCams ~ DiffSRHCenter + LogIncomeCenter + DiffSRHCenter*LogIncomeCenter, data = waves23.wide.complete)

# Add Controls 
waves23.SRH.income.3 <- lm(formula = DiffCams ~ DiffSRHCenter + LogIncomeCenter + DiffSRHCenter*LogIncomeCenter + Education_W2.2 + Age_W3 + Sex_W2 + Race_W2 + Marital_W3 + HlthInsurance_W3 + HLSelf_W3 + Spiritual_W3 + Religion_W3, data = waves23.wide.complete)

# Extract standard errors
waves23.SRH.income.1.se <- summary(waves23.SRH.income.1)$coef[,"Std. Error"]
waves23.SRH.income.2.se <- summary(waves23.SRH.income.2)$coef[,"Std. Error"]
waves23.SRH.income.3.se <- summary(waves23.SRH.income.3)$coef[,"Std. Error"]
```

```{r models-waves13-SRH-mod-income, echo = FALSE, results='hide'}

# Center diff chron 
waves13.wide.complete$DiffSRHCenter <- scale(waves13.wide.complete$DiffSRH, scale = FALSE)
waves13.wide.complete$DiffSRHCenter <- as.numeric(waves13.wide.complete$DiffSRHCenter)
# Center log income 
waves13.wide.complete$LogIncomeCenter <- scale(waves13.wide.complete$LogIncome_W1, scale = FALSE)
# Create interaction term 
waves13.wide.complete$DiffSRHxLogIncome <- waves13.wide.complete$DiffSRHCenter*waves13.wide.complete$LogIncomeCenter

# Run income model 
waves13.SRH.income.1 <- lm(formula = DiffCams ~ DiffSRHCenter + LogIncomeCenter, data = waves13.wide.complete)

# Run income model 
waves13.SRH.income.2 <- lm(formula = DiffCams ~ DiffSRHCenter + LogIncomeCenter + DiffSRHCenter*LogIncomeCenter, data = waves13.wide.complete)


# Add Controls
waves13.SRH.income.3 <- lm(formula = DiffCams ~ DiffSRHCenter + LogIncomeCenter + DiffSRHCenter*LogIncomeCenter + Education_W1.2 + Age_W3 + Sex_W1 + Race_W3 + Marital_W3 + HlthInsurance_W3 + HLSelf_W3 + Spiritual_W3 + Religion_W3, data = waves13.wide.complete)

# Extract standard errors
waves13.SRH.income.1.se <- summary(waves13.SRH.income.1)$coef[,"Std. Error"]
waves13.SRH.income.2.se <- summary(waves13.SRH.income.2)$coef[,"Std. Error"]
waves13.SRH.income.3.se <- summary(waves13.SRH.income.3)$coef[,"Std. Error"]
```

```{r models-waves12-SRH-mod-educ, echo = FALSE, results='hide'}

# Run income model 
waves12.SRH.educ.1 <- lm(formula = DiffCams ~ DiffSRHCenter + Education_W1.2, data = waves12.wide.complete)

# Run income model 
waves12.SRH.educ.2 <- lm(formula = DiffCams ~ DiffSRHCenter + Education_W1.2 + DiffSRHCenter*Education_W1.2, data = waves12.wide.complete)

# Add Controls
waves12.SRH.educ.3 <- lm(formula = DiffCams ~ DiffSRHCenter + Education_W1.2 + DiffSRHCenter*Education_W1.2 + LogIncome_W1 + Age_W2 + Sex_W1 + Race_W2 + Marital_W2 + HlthInsurance_W2 + HLSelf_W2 + Spiritual_W2 + Religion_W2, data = waves12.wide.complete)

# Extract standard errors
waves12.SRH.educ.1.se <- summary(waves12.SRH.educ.1)$coef[,"Std. Error"]
waves12.SRH.educ.2.se <- summary(waves12.SRH.educ.2)$coef[,"Std. Error"]
waves12.SRH.educ.3.se <- summary(waves12.SRH.educ.3)$coef[,"Std. Error"]
```

```{r models-waves23-SRH-mod-educ, echo = FALSE, results='hide'}

# Run income model 
waves23.SRH.educ.1 <- lm(formula = DiffCams ~ DiffSRHCenter + Education_W2.2, data = waves23.wide.complete)

# Run income model 
waves23.SRH.educ.2 <- lm(formula = DiffCams ~ DiffSRHCenter + Education_W2.2 + DiffSRHCenter*Education_W2.2, data = waves23.wide.complete)

# Add Controls 
waves23.SRH.educ.3 <- lm(formula = DiffCams ~ DiffSRHCenter + Education_W2.2 + DiffSRHCenter*Education_W2.2 + LogIncome_W2 + Age_W3 + Sex_W2 + Race_W2 + Marital_W3 + HlthInsurance_W3 + HLSelf_W3 + Spiritual_W3 + Religion_W3, data = waves23.wide.complete)

# Extract standard errors
waves23.SRH.educ.1.se <- summary(waves23.SRH.educ.1)$coef[,"Std. Error"]
waves23.SRH.educ.2.se <- summary(waves23.SRH.educ.2)$coef[,"Std. Error"]
waves23.SRH.educ.3.se <- summary(waves23.SRH.educ.3)$coef[,"Std. Error"]
```

```{r models-waves13-SRH-mod-educ, echo = FALSE, results='hide'}

# Run income model 
waves13.SRH.educ.1 <- lm(formula = DiffCams ~ DiffSRHCenter + Education_W1.2, data = waves13.wide.complete)

# Run income model 
waves13.SRH.educ.2 <- lm(formula = DiffCams ~ DiffSRHCenter + Education_W1.2 + DiffSRHCenter*Education_W1.2, data = waves13.wide.complete)

# Add Controls 
waves13.SRH.educ.3 <- lm(formula = DiffCams ~ DiffSRHCenter + Education_W1.2 + DiffSRHCenter*Education_W1.2 + LogIncome_W1 + Age_W3 + Sex_W1 + Race_W3 + Marital_W3 + HlthInsurance_W3 + HLSelf_W3 + Spiritual_W3 + Religion_W3, data = waves13.wide.complete)

# Extract standard errors
waves13.SRH.educ.1.se <- summary(waves13.SRH.educ.1)$coef[,"Std. Error"]
waves13.SRH.educ.2.se <- summary(waves13.SRH.educ.2)$coef[,"Std. Error"]
waves13.SRH.educ.3.se <- summary(waves13.SRH.educ.3)$coef[,"Std. Error"]
```

### Income as Moderator

```{r waves12-SRH-mod-income, echo = FALSE, results='asis'}
# Create regression results table
stargazer(waves12.SRH.income.1, waves12.SRH.income.2, waves12.SRH.income.3,
          title = "Waves 1 and 2 Difference in CAMs Regressed on Difference in SRH Moderated by Income", 
          column.labels = c("Model 1", "Model 2", "Model 3"), 
          covariate.labels = c("Difference in SRH", "Logged Income", 
                               "Less than High School", "HS Diploma/GED", 
                               "Some College/AA Degree", "Graduate/Professional Degree",
                               "Age at Wave 2", "Female", "Non-Hispanic Black", 
                               "Mexican American and Other Hispanic", "Other Race",
                               "Married", "Insured", "Health Locus of Control",
                               "Spirituality", "Religiosity", 
                               "Difference in SRH x Logged Income"),
          dep.var.caption  = "", 
          dep.var.labels.include = FALSE,
          model.numbers          = FALSE, 
          keep.stat = c("n", "rsq", "adj.rsq"), 
          column.sep.width = "3pt", # to reduce column width
          single.row = TRUE, # to put coefficients and standard errors on same line
          font.size = "small",
          header = FALSE, 
          notes = c("White is the reference category for race.", 
                    "Standard errors shown in parentheses.", 
                    "SRH: Self-Reported Health."), 
          notes.align = "r", 
          label = "tab:waves12-SRH-mod-income",
          star.char = c("*", "**", "***"),
          star.cutoffs = c(.05, .01, .001)) 

```

```{r plot-waves12-SRH-income-3, echo = FALSE, fig.cap= "Income Moderation Effects on Relationship Between Difference in Self-Reported Health and Difference in Total CAMs Used Between Waves 1 and 2"}
library(interactions)
interact_plot(waves12.SRH.income.3, pred = DiffSRHCenter, modx = LogIncomeCenter, 
              x.label = "Difference in Self-Reported Health", 
              y.label = "Difference in Total CAMs",
              legend.main = "Logged Income")
```

```{r waves23-SRH-mod-income, echo = FALSE, results='asis'}
# Create regression results table
stargazer(waves23.SRH.income.1, waves23.SRH.income.2, waves23.SRH.income.3, 
          title = "Waves 2 and 3 Difference in CAMs Regressed on Difference in SRH Moderated by Income", 
          column.labels = c("Model 1", "Model 2", "Model 3"), 
          covariate.labels = c("Difference in SRH", "Logged Income", 
                               "Less than High School", "HS Diploma/GED", 
                               "Some College/AA Degree", "Graduate/Professional Degree",
                               "Age at Wave 3", "Female", "Non-Hispanic Black", 
                               "Mexican American and Other Hispanic", "Other Race",
                               "Married", "Insured", "Health Locus of Control",
                               "Spirituality", "Religiosity", 
                               "Difference in SRH x Logged Income"),
          dep.var.caption  = "", 
          dep.var.labels.include = FALSE,
          model.numbers          = FALSE, 
          keep.stat = c("n", "rsq", "adj.rsq"), 
          column.sep.width = "3pt", # to reduce column width
          single.row = TRUE, # to put coefficients and standard errors on same line
          font.size = "small",
          header = FALSE, 
          notes = c("White is the reference category for race.", 
                    "Standard errors shown in parentheses.", 
                    "SRH: Self-Reported Health."), 
          notes.align = "r", 
          label = "tab:waves23-SRH-mod-income",
          star.char = c("*", "**", "***"),
          star.cutoffs = c(.05, .01, .001)) 

```

```{r plot-waves23-SRH-income-3, echo = FALSE, fig.cap= "Income Moderation Effects on Relationship Between Difference in Self-Reported Health and Difference in Total CAMs Used Between Waves 2 and 3"}
library(interactions)
interact_plot(waves23.SRH.income.3, pred = DiffSRHCenter, modx = LogIncomeCenter, 
              x.label = "Difference in Self-Reported Health", 
              y.label = "Difference in Total CAMs",
              legend.main = "Logged Income")
```

```{r waves13-SRH-mod-income, echo = FALSE, results='asis'}
# Create regression results table
stargazer(waves13.SRH.income.1, waves13.SRH.income.2, waves13.SRH.income.3,
          title = "Waves 1 and 3 Difference in CAMs Regressed on Difference in SRH Moderated by Income", 
          column.labels = c("Model 1", "Model 2", "Model 3"), 
          covariate.labels = c("Difference in SRH", "Logged Income", 
                               "Less than High School", "HS Diploma/GED", 
                               "Some College/AA Degree", "Graduate/Professional Degree",
                               "Age at Wave 3", "Female", "Non-Hispanic Black", 
                               "Mexican American and Other Hispanic", "Other Race",
                               "Married", "Insured", "Health Locus of Control",
                               "Spirituality", "Religiosity", 
                               "Difference in SRH x Logged Income"),
          dep.var.caption  = "", 
          dep.var.labels.include = FALSE,
          model.numbers          = FALSE, 
          keep.stat = c("n", "rsq", "adj.rsq"), 
          column.sep.width = "3pt", # to reduce column width
          single.row = TRUE, # to put coefficients and standard errors on same line
          font.size = "small",
          header = FALSE,
          notes = c("White is the reference category for race.", 
                    "Standard errors shown in parentheses.", 
                    "SRH: Self-Reported Health"), 
          notes.align = "r", 
          label = "tab:waves13-SRH-mod-income",
          star.char = c("*", "**", "***"),
          star.cutoffs = c(.05, .01, .001))

```

```{r plot-waves13-SRH-income-3, echo = FALSE, fig.cap= "Income Moderation Effects on Relationship Between Difference in Self-Reported Health and Difference in Total CAMs Used Between Waves 1 and 3"}
library(interactions)
interact_plot(waves13.SRH.income.3, pred = DiffSRHCenter, modx = LogIncomeCenter, 
              x.label = "Difference in Self-Reported Health", 
              y.label = "Difference in Total CAMs",
              legend.main = "Logged Income")
```

### Education as Moderator

```{r plot-waves12-SRH-educ-3, echo=FALSE, fig.cap= "Education Moderation Effects on Relationship Between Difference in SRH and Difference in Total CAMs Used Between Waves 1 and 2"}
plot_model(waves12.SRH.educ.3, 
           type = "pred", 
           terms = c("DiffSRHCenter", "Education_W1.2"), 
           title = "",
           axis.title = c("Difference in SRH", "Difference in CAMs"),
           legend.title = "Education")

```

```{r waves12-SRH-mod-educ, echo = FALSE, results='asis'}
# Create regression results table
stargazer(waves12.SRH.educ.1, waves12.SRH.educ.2, waves12.SRH.educ.3,  
          title = "Waves 1 and 2 Difference in CAMs Regressed on Difference in SRH Moderated by Education", 
          column.labels = c("Model 1", "Model 2", "Model 3"), 
          covariate.labels = c("Difference in SRH", "Less than high school", "HS Diploma/GED", 
                               "Some College/AA Degree","Graduate or Professional Degree",
                               "Logged Income", "Age at Wave 2",
                               "Female", "Non-Hispanic Black", 
                               "Mexican American and Other Hispanic", "Other Race", "Married", 
                               "Insured", "Health Locus of Control", "Spirituality", "Religiosity", 
                               "Difference in Chronic Conditions x Less than HS Diploma", 
                               "Difference in Chronic Conditions x High School Diploma/GED", 
                               "Difference in Chronic Conditions x Some College/AA Degree", 
                               "Difference in Chronic Conditions x Professional or Graduate Degree"),
          dep.var.caption  = "", 
          dep.var.labels.include = FALSE,
          model.numbers          = FALSE, 
          keep.stat = c("n", "rsq", "adj.rsq"), 
          column.sep.width = "3pt", # to reduce column width
          single.row = TRUE, # to put coefficients and standard errors on same line
          font.size = "small",
          header = FALSE,
          notes = c("College graduate is the reference category for education.", 
                    "White is the reference category for race.", 
                    "Standard errors shown in parentheses.", 
                    "SRH: Self-Reported Health."), 
          notes.align = "r", 
          float.env = "sidewaystable", 
          label = "tab:waves12-SRH-mod-educ",
          star.char = c("*", "**", "***"),
          star.cutoffs = c(.05, .01, .001))
```

```{r plot-waves23-SRH-educ-3, echo=FALSE, fig.cap= "Education Moderation Effects on Relationship Between Difference in SRH and Difference in Total CAMs Used Between Waves 2 and 3"}
plot_model(waves23.SRH.educ.3, 
           type = "pred", 
           terms = c("DiffSRHCenter", "Education_W2.2"), 
           title = "",
           axis.title = c("Difference in SRH", "Difference in CAMs"),
           legend.title = "Education")

```

```{r waves23-SRH-mod-educ, echo = FALSE, results='asis'}
# Create regression results table
stargazer(waves23.SRH.educ.1, waves23.SRH.educ.2, waves23.SRH.educ.3,  
          title = "Waves 2 and 3 Difference in CAMs Regressed on Difference in SRH Moderated by Education", 
          column.labels = c("Model 1", "Model 2", "Model 3"), 
          covariate.labels = c("Difference in SRH", "Less than high school", "HS Diploma/GED", 
                               "Some College/AA Degree", "Graduate or Professional Degree",
                               "Logged Income", "Age at Wave 2",
                               "Female", "Non-Hispanic Black", 
                               "Mexican American and Other Hispanic", "Other Race", "Married", 
                               "Insured", "Health Locus of Control", "Spirituality", "Religiosity", 
                               "Difference in Chronic Conditions x Less than HS Diploma", 
                               "Difference in Chronic Conditions x High School Diploma/GED", 
                               "Difference in Chronic Conditions x Some College/AA Degree", 
                               "Difference in Chronic Conditions x Professional or Graduate Degree"),
          dep.var.caption  = "", 
          dep.var.labels.include = FALSE,
          model.numbers          = FALSE, 
          keep.stat = c("n", "rsq", "adj.rsq"), 
          column.sep.width = "3pt", # to reduce column width
          single.row = TRUE, # to put coefficients and standard errors on same line
          font.size = "small",
          header = FALSE,
          notes = c("College graduate is the reference category for education.", 
                    "White is the reference category for race.", 
                    "Standard errors shown in parentheses.", 
                    "SRH: Self-Reported Health."), 
          notes.align = "r", 
          float.env = "sidewaystable", 
          label = "tab:waves12-SRH-mod-educ",
          star.char = c("*", "**", "***"),
          star.cutoffs = c(.05, .01, .001))
```

```{r plot-waves13-SRH-educ-3, echo=FALSE, fig.cap= "Education Moderation Effects on Relationship Between Difference in SRH and Difference in Total CAMs Used Between Waves 1 and 3"}
plot_model(waves12.SRH.educ.3, 
           type = "pred", 
           terms = c("DiffSRHCenter", "Education_W1.2"), 
           title = "",
           axis.title = c("Difference in SRH", "Difference in CAMs"),
           legend.title = "Education")

```

```{r waves13-SRH-mod-educ, echo = FALSE, results='asis'}
# Create regression results table
stargazer(waves13.SRH.educ.1, waves13.SRH.educ.2, waves13.SRH.educ.3, 
          title = "Waves 1 and 3 Difference in CAMs Regressed on Difference in SRH Moderated by Education", 
          column.labels = c("Model 1", "Model 2", "Model 3"), 
          covariate.labels = c("Difference in SRH", "Less than high school", "HS Diploma/GED", 
                               "Some College/AA Degree","Graduate or Professional Degree",
                               "Logged Income", "Age at Wave 2",
                               "Female", "Non-Hispanic Black", 
                               "Mexican American and Other Hispanic", "Other Race", "Married", 
                               "Insured", "Health Locus of Control", "Spirituality", "Religiosity", 
                               "Difference in Chronic Conditions x Less than HS Diploma", 
                               "Difference in Chronic Conditions x High School Diploma/GED", 
                               "Difference in Chronic Conditions x Some College/AA Degree", 
                               "Difference in Chronic Conditions x Professional or Graduate Degree"),
          dep.var.caption  = "", 
          dep.var.labels.include = FALSE,
          model.numbers          = FALSE, 
          keep.stat = c("n", "rsq", "adj.rsq"), 
          column.sep.width = "3pt", # to reduce column width
          single.row = TRUE, # to put coefficients and standard errors on same line
          font.size = "small",
          header = FALSE,
          notes = c("College graduate is the reference category for education.", 
                    "White is the reference category for race.", 
                    "Standard errors shown in parentheses.", 
                    "SRH: Self-Reported Health."), 
          notes.align = "r", 
          float.env = "sidewaystable", 
          label = "tab:waves12-SRH-mod-educ",
          star.char = c("*", "**", "***"),
          star.cutoffs = c(.05, .01, .001))
```
