---
title: "Mixed Model"
author: "Hannah Andrews"
date: "2/9/2022"
output:
  bookdown::pdf_document2:
    latex_engine: xelatex
bibliography: references.bib
link-citations: true
header-includes:
   - \usepackage{rotating, graphicx, longtable}
   - \extrafloats{200}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)

```

```{r, include=FALSE}
options(tinytex.verbose = TRUE)
```

```{r, echo = FALSE}
library(lme4)
library(lattice)
library(sjstats)
library(jtools)
library(ROCR)
library(sjPlot)
library(performance)
library(XML)
library(kableExtra)
library(tidyverse)
library(caTools)
library(fastDummies)
library(semptools)
library(semoutput)
library(lavaan)
library(semPlot)
library(stargazer)
library(semTable)
library(rstatix)
library(gtsummary)
library(forcats)
setwd("C:/Users/hanna/Documents/git/AHL/R/")
load("waves123.long.rda")
load("waves123.long.complete.rda")
load("waves123.wide.rda")
load("waves12.wide.complete.rda")
load("waves23.wide.complete.rda")
load("waves13.wide.complete.rda")
setwd("C:/Users/hanna/Documents/git/AHL/R/Mixed model")
# Tutorials
# https://lmudge13.github.io/sample_code/mixed_effects.html
# Converting html to pdf https://github.com/gorkang/html2latex/
```

```{r, include=FALSE}
options(tinytex.verbose = TRUE)
```

```{r path-data-recodes, echo = FALSE, results='hide'}
# Order Education levels
path.waves123.wide <- waves123.wide %>%
  mutate(waves123.wide = factor(Education_W1, levels = c("Less than High School", "HS Diploma/GED", 
                                                "Some College/AA Degree", "College Grad",
                                                "Graduate or Professional Degree"), labels = 1:5, ordered = TRUE))


# Order education levels
path.waves123.wide <- path.waves123.wide %>%
  mutate(path.waves123.wide = factor(Education_W2, levels = c("Less than High School", "HS Diploma/GED", 
                                                "Some College/AA Degree", "College Grad",
                                                "Graduate or Professional Degree"), labels = 1:5, ordered = TRUE))


# Order Education levels
path.waves123.wide <- path.waves123.wide %>%
  mutate(path.waves123.wide = factor(Education_W3, levels = c("Less than High School", "HS Diploma/GED", 
                                                "Some College/AA Degree", "College Grad",
                                                "Graduate or Professional Degree"), labels = 1:5, ordered = TRUE))


# Create dummy variables for race
path.waves123.wide <- dummy_cols(path.waves123.wide, select_columns = 'Race_W2', ignore_na = TRUE)
path.waves123.wide <- rename(path.waves123.wide, 
                             MexicanHispanic_W2 = "Race_W2_Mexican American and Other Hispanic",
                             Black_W2 = "Race_W2_Non-Hispanic Black", 
                             OtherRace_W2 = "Race_W2_Other Race",
                             White_W2 = "Race_W2_Non-Hispanic White")

# Order SRH levels
path.waves123.wide <- path.waves123.wide %>%
  mutate(waves123.wide = factor(SRH_W2, levels = c("Poor", "Fair", "Good",
                                                   "Very Good", "Excellent"), 
                                labels = 1:5, 
                                ordered = TRUE))


# Order SRH levels
path.waves123.wide <- path.waves123.wide %>%
  mutate(waves123.wide = factor(SRH_W3, levels = c("Poor", "Fair", "Good",
                                                   "Very Good", "Excellent"), 
                                labels = 1:5, 
                                ordered = TRUE))
# Order Sex_W1
path.waves123.wide <- path.waves123.wide %>% 
  mutate(waves123.wide = factor(Sex_W1, levels = c("Male", "Female"),
                                labels = 0:1, 
                                ordered = TRUE))
# Convert to numeric
path.waves123.wide$Sex_W1 <- as.numeric(path.waves123.wide$Sex_W1)
# Order Sex_W2
path.waves123.wide <- path.waves123.wide %>% 
  mutate(waves123.wide = factor(Sex_W2, levels = c("Male", "Female"),
                                labels = 0:1, 
                                ordered = TRUE))
# Convert to numeric
path.waves123.wide$Sex_W2 <- as.numeric(path.waves123.wide$Sex_W2)
# Order Sex_W3
path.waves123.wide <- path.waves123.wide %>% 
  mutate(waves123.wide = factor(Sex_W3, levels = c("Male", "Female"),
                                labels = 0:1, 
                                ordered = TRUE))
# Convert to numeric
path.waves123.wide$Sex_W3 <- as.numeric(path.waves123.wide$Sex_W3)

# Order Marital_W1
path.waves123.wide <- path.waves123.wide %>% 
  mutate(waves123.wide = factor(Marital_W1, levels = c("Not married", "Married"),
                                labels = 0:1, 
                                ordered = TRUE))
# Convert to numeric
path.waves123.wide$Marital_W1 <- as.numeric(path.waves123.wide$Marital_W1)
# Order Marital_W2
path.waves123.wide <- path.waves123.wide %>% 
  mutate(waves123.wide = factor(Marital_W2, levels = c("Not married", "Married"),
                                labels = 0:1, 
                                ordered = TRUE))
# Convert to numeric
path.waves123.wide$Marital_W2 <- as.numeric(path.waves123.wide$Marital_W2)
# Order marital_W3
path.waves123.wide <- path.waves123.wide %>% 
  mutate(waves123.wide = factor(Marital_W3, levels = c("Not married", "Married"),
                                labels = 0:1, 
                                ordered = TRUE))
# Convert to numeric
path.waves123.wide$Marital_W3 <- as.numeric(path.waves123.wide$Marital_W3)

# Order hlthinsurance_W1
path.waves123.wide <- path.waves123.wide %>% 
  mutate(waves123.wide = factor(HlthInsurance_W1, levels = c("Uninsured", "Insured"),
                                labels = 0:1, 
                                ordered = TRUE))
# Convert to numeric
path.waves123.wide$HlthInsurance_W1 <- as.numeric(path.waves123.wide$HlthInsurance_W1)
# Order hlthinsurance_W2
path.waves123.wide <- path.waves123.wide %>% 
  mutate(waves123.wide = factor(HlthInsurance_W2, levels = c("Uninsured", "Insured"),
                                labels = 0:1, 
                                ordered = TRUE))
# Convert to numeric
path.waves123.wide$HlthInsurance_W2 <- as.numeric(path.waves123.wide$HlthInsurance_W2)
# Order hlthinsurance_W3
path.waves123.wide <- path.waves123.wide %>% 
  mutate(waves123.wide = factor(HlthInsurance_W3, levels = c("Uninsured", "Insured"),
                                labels = 0:1, 
                                ordered = TRUE))
# Convert to numeric
path.waves123.wide$HlthInsurance_W3 <- as.numeric(path.waves123.wide$HlthInsurance_W3)

# order anychron_W1
path.waves123.wide <- path.waves123.wide %>% 
  mutate(waves123.wide = factor(AnyChron_W1, levels = c("Uninsured", "Insured"),
                                labels = 0:1, 
                                ordered = TRUE))
# order anychron_W1
path.waves123.wide <- path.waves123.wide %>% 
  mutate(waves123.wide = factor(AnyChron_W2, levels = c("Uninsured", "Insured"),
                                labels = 0:1, 
                                ordered = TRUE))
# order anychron_W1
path.waves123.wide <- path.waves123.wide %>% 
  mutate(waves123.wide = factor(AnyChron_W3, levels = c("Uninsured", "Insured"),
                                labels = 0:1, 
                                ordered = TRUE))
# Convert mb to factor 
path.waves123.wide$mindbody_W1 <- cut(path.waves123.wide$mindbody_W1, 2, labels = c("No", "Yes"))
# Order mb 1
path.waves123.wide <- path.waves123.wide %>% 
  mutate(mindbody_W1 = factor(mindbody_W1, levels = c("No", "Yes"),
                                labels = 0:1, 
                                ordered = TRUE))
# Convert mb2 to factor 
path.waves123.wide$mindbody_W2 <- cut(path.waves123.wide$mindbody_W2, 2, labels = c("No", "Yes"))
# Order mb 1
path.waves123.wide <- path.waves123.wide %>% 
  mutate(mindbody_W2 = factor(mindbody_W2, levels = c("No", "Yes"),
                                labels = 0:1, 
                                ordered = TRUE))
# Convert mb2 to factor 
path.waves123.wide$mindbody_W3 <- cut(path.waves123.wide$mindbody_W3, 2, labels = c("No", "Yes"))
# Order mb 1
path.waves123.wide <- path.waves123.wide %>% 
  mutate(mindbody_W3 = factor(mindbody_W3, levels = c("No", "Yes"),
                                labels = 0:1, 
                                ordered = TRUE))

# Convert altmed to factor 
path.waves123.wide$altmed_W1 <- cut(path.waves123.wide$altmed_W1, 2, labels = c("No", "Yes"))
# Order altmed 1
path.waves123.wide <- path.waves123.wide %>% 
  mutate(altmed_W1 = factor(altmed_W1, levels = c("No", "Yes"),
                                labels = 0:1, 
                                ordered = TRUE))
# Convert altmed2 to factor 
path.waves123.wide$altmed_W2 <- cut(path.waves123.wide$altmed_W2, 2, labels = c("No", "Yes"))
# Order altmed 2
path.waves123.wide <- path.waves123.wide %>% 
  mutate(altmed_W2 = factor(altmed_W2, levels = c("No", "Yes"),
                                labels = 0:1, 
                                ordered = TRUE))
# Convert mb2 to factor 
path.waves123.wide$altmed_W3 <- cut(path.waves123.wide$altmed_W3, 2, labels = c("No", "Yes"))
# Order altmed 3
path.waves123.wide <- path.waves123.wide %>% 
  mutate(altmed_W3 = factor(altmed_W3, levels = c("No", "Yes"),
                                labels = 0:1, 
                                ordered = TRUE))

# Convert pna to factor 
path.waves123.wide$pna_W1 <- cut(path.waves123.wide$pna_W1, 2, labels = c("No", "Yes"))
# Order pna 1
path.waves123.wide <- path.waves123.wide %>% 
  mutate(pna_W1 = factor(pna_W1, levels = c("No", "Yes"),
                                labels = 0:1, 
                                ordered = TRUE))
# Convert pna2 to factor 
path.waves123.wide$pna_W2 <- cut(path.waves123.wide$pna_W2, 2, labels = c("No", "Yes"))
# Order pna 3
path.waves123.wide <- path.waves123.wide %>% 
  mutate(pna_W2 = factor(pna_W2, levels = c("No", "Yes"),
                                labels = 0:1, 
                                ordered = TRUE))
# Convert pna3 to factor 
path.waves123.wide$pna_W3 <- cut(path.waves123.wide$pna_W3, 2, labels = c("No", "Yes"))
# Order pna 3
path.waves123.wide <- path.waves123.wide %>% 
  mutate(pna_W3 = factor(pna_W3, levels = c("No", "Yes"),
                                labels = 0:1, 
                                ordered = TRUE))

# Convert manipulative to factor 
path.waves123.wide$manipulative_W1 <- cut(path.waves123.wide$manipulative_W1, 2, labels = c("No", "Yes"))
# Order manipulative 1
path.waves123.wide <- path.waves123.wide %>% 
  mutate(manipulative_W1 = factor(manipulative_W1, levels = c("No", "Yes"),
                                labels = 0:1, 
                                ordered = TRUE))
# Convert manipulative2 to factor 
path.waves123.wide$manipulative_W2 <- cut(path.waves123.wide$manipulative_W2, 2, labels = c("No", "Yes"))
# Order manipulative 3
path.waves123.wide <- path.waves123.wide %>% 
  mutate(manipulative_W2 = factor(manipulative_W2, levels = c("No", "Yes"),
                                labels = 0:1, 
                                ordered = TRUE))
# Convert manipulative3 to factor 
path.waves123.wide$manipulative_W3 <- cut(path.waves123.wide$manipulative_W3, 2, labels = c("No", "Yes"))
# Order manipulative 3
path.waves123.wide <- path.waves123.wide %>% 
  mutate(manipulative_W3 = factor(manipulative_W3, levels = c("No", "Yes"),
                                labels = 0:1, 
                                ordered = TRUE))
```

```{r listwise-delete-path-data, echo =FALSE}
myvars <- c("mindbody_W2", "mindbody_W3", "altmed_W2", "altmed_W3", "pna_W2", "pna_W3", "manipulative_W2", "manipulative_W3", "totalCams_W2", "totalCams_W3", "SumChron_W2", "SumChron_W3", "SRH_W2", "SRH_W3", "LogIncome_W1", "Education_W1", "Sex_W1", "Age_W2", "Age_W3", "Marital_W2", "Marital_W3", "HlthInsurance_W2", "HlthInsurance_W3", "HLSelf_W2", "HLSelf_W3", "Spiritual_W2", "Spiritual_W3", "Religion_W2", "Religion_W3", "MexicanHispanic_W2", "Black_W2", "OtherRace_W2", "AnyChron_W2", "AnyChron_W3")

path.complete <- path.waves123.wide[myvars]

path.complete <- path.complete[complete.cases(path.complete),]

```

```{r, echo = FALSE}
require(foreign)
write.dta(path.complete, "mydata.dta")
library(Statamarkdown)

stataexe <- "C:/Program Files/Stata17/StataBE-64.exe"
knitr::opts_chunk$set(engine.path=list(stata=stataexe))

```

# Three step total CAMs sum chron



```{stata, include=FALSE}
use mydata.dta

# remove uppercase from variables
rename (LogIncome_W1 Education_W1 Sex_W1 SumChron_W2 Age_W2 Marital_W2 HlthInsurance_W2 HLSelf_W2 Spiritual_W2 Religion_W2 MexicanHispanic_W2 Black_W2 OtherRace_W2 SumChron_W3 Age_W3 Marital_W3 HlthInsurance_W3 HLSelf_W3 Spiritual_W3 Religion_W3) (logincome_W1 education_W1 sex_W1 sumchron_W2 age_W2 marital_W2 hlthinsurance_W2 hlself_W2 spiritual_W2 religion_W2 mexicanhispanic_W2 black_W2 otherrace_W2 sumchron_W3 age_W3 marital_W3 hlthinsurance_W3 hlself_W3 spiritual_W3 religion_W3)

rename(totalCams_W2 totalCams_W3)(totalcams_W2 totalcams_W3)

# Run gsem
gsem(totalcams_W2 <- logincome_W1 education_W1 sex_W1 age_W2 marital_W2 hlthinsurance_W2 hlself_W2 spiritual_W2 religion_W2 mexicanhispanic_W2 black_W2 otherrace_W2, poisson) (sumchron_W2 <- logincome_W1 education_W1 sex_W1 age_W2 marital_W2 hlthinsurance_W2 hlself_W2 spiritual_W2 religion_W2 mexicanhispanic_W2 black_W2 otherrace_W2, poisson) (totalcams_W3 <- logincome_W1 education_W1 sumchron_W2 totalcams_W2 age_W3 sex_W1 marital_W3 hlthinsurance_W3 hlself_W3 spiritual_W3 religion_W3 mexicanhispanic_W2 black_W2 otherrace_W2, poisson) (sumchron_W3 <- logincome_W1 education_W1 sumchron_W2 totalcams_W2 age_W3 sex_W1 marital_W3 hlthinsurance_W3 hlself_W3 spiritual_W3 religion_W3 mexicanhispanic_W2 black_W2 otherrace_W2, poisson)

# save results as dataframe
regsave using totcamschron, pval ci

```

```{r read-in-totcams-chron-gsem-results, echo=FALSE}


```




```{r model-mb-chron, echo = FALSE, results='hide', fig.show='hide'}
model <- '
# Regressions
# Direct effect - log income 
mindbody_W3 ~ a*LogIncome_W1 
AnyChron_W3 ~ b*LogIncome_W1
# Direct Effect - Education
mindbody_W3 ~ c*Education_W1
AnyChron_W3 ~ d*Education_W1
# Mediator effects - Income 
AnyChron_W2 ~ e*LogIncome_W1 
mindbody_W3 ~ f*AnyChron_W2
mindbody_W2 ~ g*LogIncome_W1
AnyChron_W3 ~ h*mindbody_W2
# Mediator effects - Education
mindbody_W2 ~ i*Education_W1
AnyChron_W2 ~ j*Education_W1 
# Control for previous wave
mindbody_W3 ~ mindbody_W2
AnyChron_W3 ~ AnyChron_W2
# Indirect effect 
ef := e*f
gh := g*h
jf := j*f
ih := i*h
# total effect
total1 := a + (e*f)
total2 := b + (g*h)
total3 := c + (j*f)
total4 := d + (i*h)
# Controls
mindbody_W2 ~ Sex_W1 + Age_W2 + Marital_W2 + HlthInsurance_W2 + HLSelf_W2 + Spiritual_W2 + Religion_W2 + MexicanHispanic_W2 + Black_W2 + OtherRace_W2
AnyChron_W2 ~ Sex_W1 + Age_W2 + Marital_W2 + MexicanHispanic_W2 + Black_W2 + OtherRace_W2
mindbody_W3 ~ Age_W3 + Sex_W1 + Marital_W3 + HlthInsurance_W3 + HLSelf_W3 + Spiritual_W3 + Religion_W3 + MexicanHispanic_W2 + Black_W2 + OtherRace_W2
AnyChron_W3 ~ Age_W3 + Sex_W1 + Marital_W3 + MexicanHispanic_W2 + Black_W2 + OtherRace_W2
# Covariances
mindbody_W2 ~~ AnyChron_W2
mindbody_W3 ~~ AnyChron_W3
'


# Run model and get summary and fit statistics
set.seed(1234)
model.summ <- sem(model, data = path.complete, ordered = c("mindbody_W2", "mindbody_W3", "AnyChron_W2", "AnyChron_W3"), se = "bootstrap", estimator = "DWLS")
summary(model.summ, standardized = TRUE)
fitMeasures(model.summ, c("cfi", "rmsea", "srmr"))
#modificationindices(model.summ)

# Create object with model fit measures
fit.mb.chron <- lavInspect(model.summ, what = "fit")

# Create object with parameter estimates
est.mb.chron <- parameterEstimates(model.summ, boot.ci.type = "bca.simple", standardized = TRUE)


m <- matrix(NA, 4, 3)
m[1, 1] <- "LogIncome_W1"
m[4, 1] <- "Education_W1"
m[2, 2] <- "mindbody_W2"
m[3, 2] <- "AnyChron_W2"
m[1, 3] <- "mindbody_W3"
m[4, 3] <- "AnyChron_W3"

test <- layout_matrix(LogIncome_W1 = c(1,1),
                      Education_W1 = c(4,1),
                      mindbody_W2 = c(2,2),
                      AnyChron_W2 = c(3,2),
                      mindbody_W3 = c(1,3),
                      AnyChron_W3 = c(4,3))

# Drop controls from path diagram
path_dia <- semptools::drop_nodes(
                object = semPlotModel(model.summ),
                nodes = c("Age_W3", "Sex_W1", "Marital_W3", "HlthInsurance_W3", "HLSelf_W3", "Spiritual_W3", "Religion_W3", "MexicanHispanic_W2", "Black_W2", "OtherRace_W2", "Age_W2", "Marital_W2", "HlthInsurance_W2", "HLSelf_W2", "Spiritual_W2", "Religion_W2"))

# Create path diagram
path_dia2 <- semPaths(path_dia, whatLabels = "std",
           sizeMan = 8,
           edge.label.cex = .8,
           edge.color = "black",
           style = "ram",
           layout = m, 
           exoCov = FALSE,
           nCharNodes = 0, nCharEdges = 0)

# Create list to rearrange positions of node edges that were blocking each other
my_position_list <- c("mindbody_W3 ~ Education_W1" = .20, 
                      "AnyChron_W3 ~ LogIncome_W1" = .75)
# Change label position
path_dia3 <- set_edge_label_position(path_dia2, my_position_list)

path_dia4 <- change_node_label(path_dia3,
                           c(LogIncome_W1 = "Income W1",
                             Education_W1 = "Education W1",
                             mindbody_W2 = "Mind Body W2",
                             AnyChron_W2 = "Any Chron W2", 
                             mindbody_W3 = "Mind Body W3",
                             AnyChron_W3 = "Any Chron W3"),
                           label.cex = 1.1)

path_dia5 <- mark_sig(path_dia4, model.summ, alpha = c("(n.s.)" = 1.00, "*" = .05))

```

```{r path-mb-chron, echo = FALSE, fig.cap="Path Model: SES, Mind-Body Medicine, and Chronic Conditions"}
# Create final plot
plot(path_dia5)
```

```{r de-mb-chron, echo = FALSE}
# Create Direct Effects Table 
parameterEstimates(model.summ, boot.ci.type = "bca.simple", standardized=TRUE) %>% 
  filter(op == "~") %>%  
  select(Outcome=lhs, Indicator=rhs, B=est, 'Lower CI'= ci.lower, 'Upper CI'= ci.upper, 'p-value'=pvalue, Beta=std.all) %>%
  as.data.frame() %>% 
  mutate(Indicator = replace(Indicator, Indicator == "mindbody_W2", "Mind Body Wave 2")) %>% 
  mutate(Indicator = replace(Indicator, Indicator == "mindbody_W3", "Mind Body Wave 3")) %>% 
  mutate(Indicator = replace(Indicator, Indicator == "altmed_W2", "Alt Med Wave 2")) %>% 
  mutate(Indicator = replace(Indicator, Indicator == "altmed_W3", "Alt Med Wave 3")) %>% 
  mutate(Indicator = replace(Indicator, Indicator == "pna_W2", "PNA Wave 2")) %>%
  mutate(Indicator = replace(Indicator, Indicator == "pna_W3", "PNA Wave 3")) %>% 
  mutate(Indicator = replace(Indicator, Indicator == "manipulative_W2", "Manipulative Wave 2")) %>%
  mutate(Indicator = replace(Indicator, Indicator == "manipulative_W3", "Manipulative Wave 3")) %>%
  mutate(Indicator = replace(Indicator, Indicator == "totalCams_W2", "Total CAMs Wave 2")) %>%
  mutate(Indicator = replace(Indicator, Indicator == "totalCams_W3", "Total CAMs Wave 3")) %>%
  mutate(Indicator = replace(Indicator, Indicator == "SumChron_W2", "Sum Chron Wave 2")) %>%
  mutate(Indicator = replace(Indicator, Indicator == "SumChron_W3", "Sum Chron Wave 3")) %>% 
  mutate(Indicator = replace(Indicator, Indicator == "SRH_W2", "SRH Wave 2")) %>%
  mutate(Indicator = replace(Indicator, Indicator == "SRH_W3", "SRH Wave 3")) %>% 
  mutate(Indicator = replace(Indicator, Indicator == "LogIncome_W1", "Logged Income Wave 1")) %>%
  mutate(Indicator = replace(Indicator, Indicator == "Education_W1", "Education Wave 1")) %>%
  mutate(Indicator = replace(Indicator, Indicator == "Sex_W1", "Sex")) %>%
  mutate(Indicator = replace(Indicator, Indicator == "Age_W2", "Age Wave 2")) %>%
  mutate(Indicator = replace(Indicator, Indicator == "Age_W3", "Age Wave 3")) %>%
  mutate(Indicator = replace(Indicator, Indicator == "Marital_W2", "Married Wave 2")) %>%
  mutate(Indicator = replace(Indicator, Indicator == "Marital_W3", "Married Wave 3")) %>%
  mutate(Indicator = replace(Indicator, Indicator == "HlthInsurance_W2", "Health Insurance Wave 2")) %>%
  mutate(Indicator = replace(Indicator, Indicator == "HlthInsurance_W3", "Health Insurance Wave 3")) %>%
  mutate(Indicator = replace(Indicator, Indicator == "HLSelf_W2", "Health Locus of Control Wave 2")) %>%
  mutate(Indicator = replace(Indicator, Indicator == "HLSelf_W3", "Health Locus of Control Wave 3")) %>%
  mutate(Indicator = replace(Indicator, Indicator == "Spiritual_W2", "Spirituality Wave 2")) %>%
  mutate(Indicator = replace(Indicator, Indicator == "Spiritual_W3", "Spirituality Wave 3")) %>%
  mutate(Indicator = replace(Indicator, Indicator == "Religion_W2", "Religiosity Wave 2")) %>%
  mutate(Indicator = replace(Indicator, Indicator == "Religion_W3", "Religiosity Wave 3")) %>%
  mutate(Indicator = replace(Indicator, Indicator == "MexicanHispanic_W2", "Mexican American/Hispanic")) %>%
  mutate(Indicator = replace(Indicator, Indicator == "Black_W2", "Black")) %>%
  mutate(Indicator = replace(Indicator, Indicator == "OtherRace_W2", "Other Race")) %>%
  mutate(Outcome = replace(Outcome, Outcome == "mindbody_W2", "Mind Body Wave 2")) %>% 
  mutate(Outcome = replace(Outcome, Outcome == "mindbody_W3", "Mind Body Wave 3")) %>% 
  mutate(Outcome = replace(Outcome, Outcome == "altmed_W2", "Alt Med Wave 2")) %>% 
  mutate(Outcome = replace(Outcome, Outcome == "altmed_W3", "Alt Med Wave 3")) %>% 
  mutate(Outcome = replace(Outcome, Outcome == "pna_W2", "PNA Wave 2")) %>%
  mutate(Outcome = replace(Outcome, Outcome == "pna_W3", "PNA Wave 3")) %>% 
  mutate(Outcome = replace(Outcome, Outcome == "manipulative_W2", "Manipulative Wave 2")) %>%
  mutate(Outcome = replace(Outcome, Outcome == "manipulative_W3", "Manipulative Wave 3")) %>%
  mutate(Outcome = replace(Outcome, Outcome == "totalCams_W2", "Total CAMs Wave 2")) %>%
  mutate(Outcome = replace(Outcome, Outcome == "totalCams_W3", "Total CAMs Wave 3")) %>%
  mutate(Outcome = replace(Outcome, Outcome == "SumChron_W2", "Sum Chron Wave 2")) %>%
  mutate(Outcome = replace(Outcome, Outcome == "SumChron_W3", "Sum Chron Wave 3")) %>% 
  mutate(Outcome = replace(Outcome, Outcome == "SRH_W2", "SRH Wave 2")) %>%
  mutate(Outcome = replace(Outcome, Outcome == "SRH_W3", "SRH Wave 3")) %>% 
  mutate(Outcome = replace(Outcome, Outcome == "LogIncome_W1", "Logged Income Wave 1")) %>%
  mutate(Outcome = replace(Outcome, Outcome == "Education_W1", "Education Wave 1")) %>%
  mutate(Outcome = replace(Outcome, Outcome == "Sex_W1", "Sex")) %>%
  mutate(Outcome = replace(Outcome, Outcome == "Age_W2", "Age Wave 2")) %>%
  mutate(Outcome = replace(Outcome, Outcome == "Age_W3", "Age Wave 3")) %>%
  mutate(Outcome = replace(Outcome, Outcome == "Marital_W2", "Married Wave 2")) %>%
  mutate(Outcome = replace(Outcome, Outcome == "Marital_W3", "Married Wave 3")) %>%
  mutate(Outcome = replace(Outcome, Outcome == "HlthInsurance_W2", "Health Insurance Wave 2")) %>%
  mutate(Outcome = replace(Outcome, Outcome == "HlthInsurance_W3", "Health Insurance Wave 3")) %>%
  mutate(Outcome = replace(Outcome, Outcome == "HLSelf_W2", "Health Locus of Control Wave 2")) %>%
  mutate(Outcome = replace(Outcome, Outcome == "HLSelf_W3", "Health Locus of Control Wave 3")) %>%
  mutate(Outcome = replace(Outcome, Outcome == "Spiritual_W2", "Spirituality Wave 2")) %>%
  mutate(Outcome = replace(Outcome, Outcome == "Spiritual_W3", "Spirituality Wave 3")) %>%
  mutate(Outcome = replace(Outcome, Outcome == "Religion_W2", "Religiosity Wave 2")) %>%
  mutate(Outcome = replace(Outcome, Outcome == "Religion_W3", "Religiosity Wave 3")) %>%
  mutate(Outcome = replace(Outcome, Outcome == "MexicanHispanic_W2", "Mexican American/Hispanic")) %>%
  mutate(Outcome = replace(Outcome, Outcome == "Black_W2", "Black")) %>%
  mutate(Outcome = replace(Outcome, Outcome == "OtherRace_W2", "Other Race")) %>% 
  add_significance(p.col = "p-value",
                   output.col = "Significance Level",
                   cutpoints = c(0, 0.001, 0.01, 0.05, 1),
                   symbols = c("***", "**", "*", " ")) %>% 
  dplyr::relocate("Significance Level", .after = "p-value") %>%  
  knitr::kable(digits = 3, 
               booktabs=TRUE, 
               caption="Direct Effects: SES, Mind-Body Medicine, and Chronic Conditions",
               escape = F, 
               col.names = c("Outcome", "Indicator", "\\textit{b}", "Lower CI", 
                             "Upper CI", "\\textit{p}-value", " ", "$\\beta$")) %>%
  kable_classic(html_font = "CMU Serif") %>%
  kable_styling(latex_options = c("striped"),
                font_size = 7) %>% 
  footnote(general = c("\\\\textit{b} = unstandardized coefficient. 
                       $\\\\beta$ = standardized coefficient."),
           symbol = c("$p<.05.$", "$p<.01.$", "$p<.001.$"),
           symbol_manual = c("$^{*}$", "$^{**}$", "$^{***}$"),
           threeparttable = TRUE, 
           footnote_as_chunk = TRUE, 
           escape = F) %>%  
  kableExtra::landscape() 
```

```{r create-ie-mb, echo = FALSE, results='hide'}
parameterEstimates(model.summ, boot.ci.type = "bca.simple", standardized=TRUE) %>% 
  filter(op == ":=")

# Create Indirect Effects Table 

# Convert output to dataframe with desired rows and columns 
tab.IE.mb <- parameterEstimates(model.summ, boot.ci.type = "bca.simple", standardized=TRUE) %>% 
  filter(op == ":=") %>% 
  select('Path'=lhs, B=est, 'Lower CI'= ci.lower, 'Upper CI'= ci.upper,'p-value'=pvalue, Beta=std.all) %>%
  as.data.frame() 


# create a vector rows in desired order
x <- c("ef", "total1", "gh", "total2", "jf", "total3", "ih", "total4")

# Reorder rows
tab.IE.mb <- tab.IE.mb %>%
  slice(match(x, Path))
```

```{r ie-mb-chron, echo=FALSE}
tab.IE.mb %>% 
  mutate(Path = replace(Path, Path == "ef", "Indirect Effect: Income \U2192 Chronic Conditions \U2192 Mind-Body Medicine")) %>%
  mutate(Path = replace(Path, Path == "total1", "Total Effect: Income \U2192 Chronic Conditions \U2192 Mind-Body Medicine")) %>%
  mutate(Path = replace(Path, Path == "gh", "Indirect Effect: Income \U2192 Mind-Body Medicine \U2192 Chronic Conditions")) %>%
  mutate(Path = replace(Path, Path == "total2", "Total Effect: Income \U2192 Mind-Body Medicine \U2192 Chronic Conditions")) %>%
  mutate(Path = replace(Path, Path == "jf", "Indirect Effect: Education \U2192 Chronic Conditions \U2192 Mind-Body Medicine")) %>%
  mutate(Path = replace(Path, Path == "total3", "Total Effect: Education \U2192 Chronic Conditions \U2192 Mind-Body Medicine")) %>%
  mutate(Path = replace(Path, Path == "ih", "Indirect Effect: Education \U2192 Mind-Body Medicine \U2192 Chronic Conditions")) %>%
  mutate(Path = replace(Path, Path == "total4", "Total Effect: Education \U2192 Mind-Body Medicine \U2192 Chronic Conditions")) %>% 
  add_significance(p.col = "p-value",
                   output.col = "Significance Level",
                   cutpoints = c(0, 0.001, 0.01, 0.05, 1),
                   symbols = c("***", "**", "*", " ")) %>% 
  dplyr::relocate("Significance Level", .after = "p-value") %>%
  knitr::kable(digits = 3, 
               booktabs=TRUE, 
               escape = F, 
               col.names = c("Path", "\\textit{b}", "Lower CI", "Upper CI", "\\textit{p}-value", " ", "$\\beta$"),
               caption="Indirect and Total Effects: SES, Mind-Body Medicines, and Chronic Conditions") %>%
  kable_classic(html_font = "CMU Serif") %>%
  kable_styling(latex_options = c("striped")) %>% 
  footnote(general = c("\\\\textit{b} = unstandardized coefficient. 
                       $\\\\beta$ = standardized coefficient."),
           symbol = c("$p<.05.$", "$p<.01.$", "$p<.001.$"),
           symbol_manual = c("$^{*}$", "$^{**}$", "$^{***}$"),
           threeparttable = TRUE, 
           footnote_as_chunk = TRUE, 
           escape = F) %>% 
  kableExtra::landscape()
```

```{r fit-mb-chron, echo = FALSE}
# Create fit statistics table 
fitMeasures(model.summ, c("chisq", "df", "pvalue", "cfi", "tli", "rmsea",  "srmr")) %>%
  as.data.frame() %>% 
  t() %>%  
  knitr::kable(digits = 3, 
               booktabs=TRUE, 
               escape = F, 
               caption="Fit Statistics: SES, Chronic Conditions, and Mind-Body Medicines Path Model",
               col.names=c("$\\chi^2$","df","\\textit{p}-value", "CFI", "TLI", "RMSEA", "SRMR")) %>%  
  kable_classic(html_font = "CMU Serif") %>%
  kable_styling(latex_options = c("striped")) %>% 
  add_footnote(c("CFI = Comparitive Fit Index.", "TLI = Tucker Lewis-Index.", "RMSEA = root mean square error of approximation.", "SRMR = standardized root mean square residual."), notation = "none")
```

```{r models-waves12-chron-mod-income, echo = FALSE, results='hide'}

# Center diff chron 
waves12.wide.complete$DiffChronCenter <- scale(waves12.wide.complete$DiffChron, scale = FALSE)
waves12.wide.complete$DiffChronCenter <- as.numeric(waves12.wide.complete$DiffChronCenter)
# Center log income 
waves12.wide.complete$LogIncomeCenter <- scale(waves12.wide.complete$LogIncome_W1, scale = FALSE)
waves12.wide.complete$LogIncomeCenter <- as.numeric(waves12.wide.complete$LogIncomeCenter)
# Create interaction term 
waves12.wide.complete$DiffChronxLogIncome <- waves12.wide.complete$DiffChronCenter*waves12.wide.complete$LogIncomeCenter

# Run income model 
waves12.chron.income.1 <- lm(formula = DiffCams ~ DiffChronCenter + LogIncomeCenter, data = waves12.wide.complete)

# Run income model 
waves12.chron.income.2 <- lm(formula = DiffCams ~ DiffChronCenter + LogIncomeCenter + DiffChronCenter*LogIncomeCenter, data = waves12.wide.complete)

# Add Controls 
waves12.chron.income.3 <- lm(formula = DiffCams ~ DiffChronCenter + LogIncomeCenter + DiffChronCenter*LogIncomeCenter + Education_W1.2 + Age_W2 + Sex_W1 + Race_W2 + Marital_W2 + HlthInsurance_W2 + HLSelf_W2 + Spiritual_W2 + Religion_W2, data = waves12.wide.complete)

# Extract standard errors
waves12.chron.income.1.se <- summary(waves12.chron.income.1)$coef[,"Std. Error"]
waves12.chron.income.2.se <- summary(waves12.chron.income.2)$coef[,"Std. Error"]
waves12.chron.income.3.se <- summary(waves12.chron.income.3)$coef[,"Std. Error"]

noy1control <- tab_model(waves12.chron.income.1, waves12.chron.income.2, waves12.chron.income.3)
```

```{r models-waves12-chron-mod-income, echo = FALSE, results='hide'}

# Center diff chron 
waves12.wide.complete$DiffChronCenter <- scale(waves12.wide.complete$DiffChron, scale = FALSE)
waves12.wide.complete$DiffChronCenter <- as.numeric(waves12.wide.complete$DiffChronCenter)
# Center log income 
waves12.wide.complete$LogIncomeCenter <- scale(waves12.wide.complete$LogIncome_W1, scale = FALSE)
waves12.wide.complete$LogIncomeCenter <- as.numeric(waves12.wide.complete$LogIncomeCenter)
# Create interaction term 
waves12.wide.complete$DiffChronxLogIncome <- waves12.wide.complete$DiffChronCenter*waves12.wide.complete$LogIncomeCenter

# Run income model 
waves12.chron.income.1 <- lm(formula = DiffCams ~ DiffChronCenter + LogIncomeCenter + SumChron_W1, data = waves12.wide.complete)

# Run income model 
waves12.chron.income.2 <- lm(formula = DiffCams ~ DiffChronCenter + LogIncomeCenter + SumChron_W1 + DiffChronCenter*LogIncomeCenter, data = waves12.wide.complete)

# Add Controls 
waves12.chron.income.3 <- lm(formula = DiffCams ~ DiffChronCenter + LogIncomeCenter + SumChron_W1 + DiffChronCenter*LogIncomeCenter + Education_W1.2 + Age_W2 + Sex_W1 + Race_W2 + Marital_W2 + HlthInsurance_W2 + HLSelf_W2 + Spiritual_W2 + Religion_W2, data = waves12.wide.complete)

# Extract standard errors
waves12.chron.income.1.se <- summary(waves12.chron.income.1)$coef[,"Std. Error"]
waves12.chron.income.2.se <- summary(waves12.chron.income.2)$coef[,"Std. Error"]
waves12.chron.income.3.se <- summary(waves12.chron.income.3)$coef[,"Std. Error"]

y1control <- tab_model(waves12.chron.income.1, waves12.chron.income.2, waves12.chron.income.3)
```

```{r, echo = FALSE}
# code change in anychron from 0 to 1 as 1, 

```

