---
title: "LCA"
author: "Hannah Andrews"
date: "11/13/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
dir <- "C:/Users/hanna/Documents/git/AHL/R"
setwd(dir)

# Load Libraries ####
library(expss)
library(Hmisc)
library(dplyr)
library(summarytools)
library(magrittr)
library(tidyverse)
library(mosaic)
library(lattice)
library(ggplot2)
library(scales)
library(ggthemes)
library(LCA)
library(poLCA)
library(haven)
library(labelled)

# Load all MIDUS data into the global environment ####
# This chunk reads in the MIDUS1 Stata .dta file, subsets the data to only include CAMs, and restricts the data to complete cases. 

# Read in MIDUS1 data and subset to complete cases on CAMs
# Read in stata file for MIDUS 1
path <- ("C:/Users/hanna/Documents/git/AHL/Stata/data-cleaning/MIDUS1.dta")
M1 <- read_dta(path)
acamsList <- c("acam1", "acam2", "acam3", "acam4", "acam5", "acam6", "acam7", 
               "acam8", "acam9", "acam10", "acam11", "acam13", "acam14", 
               "acam21")

acams <- M1[acamsList] # Subset MIDUS1 - only include CAMs.

# Remove attributes from acams data - created in Stata (labels and data notes). They're (were) producing an error with bart_spher.
acams <- remove_attributes(acams, "label")
acams <- remove_attributes(acams, "notes")

str(acams)
head(acams)

# Rename columns 
acams <- dplyr::rename(acams, 
                          aAcupuncture = acam1, 
                          aBiofeedback = acam2,
                          aChiropractic = acam3,
                          aEnergyHeal = acam4,
                          aExerciseMove = acam5,
                          aHerbal = acam6,
                          aVitamins = acam7,
                          aHomeopathy = acam8,
                          aHypnosis = acam9,
                          aImageryTech = acam10,
                          aMassage = acam11,
                          aRelaxMeditate = acam13,
                          aSpecialDiet = acam14,
                          aPraySpirit = acam21)
head(acams)
# Keep only complete cases
acams=acams[complete.cases(acams),]
str(acams)

# on dataframes in poLCA: A data frame containing variables in formula. Manifest variables must contain only integer values, and must be coded with consecutive values from 1 to the maximum number of outcomes for each variable. All missing values should be entered as NA
acamslca <- acams + 1
head (acamslca)
```
# MIDUS 1 LCA 

```{r, echo = FALSE}
# Different example: https://statistics.ohlsen-web.de/latent-class-analysis-polca/
# Code below: https://stackoverflow.com/questions/48793923/finding-the-best-lca-model-in-polca-r-package
library(poLCA)
library(foreach)
library(doParallel)

acl <- function(df,   #a data.frame with your data 
                k,       #the maximum number of classes to fit
                formula) {  
  foreach(i=1:k, .packages="poLCA") %dopar% poLCA(formula, df, nclass=i, 
                                                  nrep = 100
  )
}

f <- cbind(aAcupuncture, aBiofeedback, aChiropractic, aEnergyHeal, aExerciseMove, aHerbal, 
           aVitamins, aHomeopathy, aHypnosis, aImageryTech, aMassage, 
           aRelaxMeditate, aSpecialDiet, aPraySpirit) ~ 1

# Creates a table that compares the models. 
compare_classes_acl <- function(model) {
  entropy<-function (p) sum(-p*log(p)) #to assess the quality of classification
  table_LCA <- data.frame(Model=0, AIC=0, BIC=0, MaxLogLikelihood=0, LikelihoodRatio=0, Entropy=0, PropInSmallestClass=0)   #empty data.frame to prealocate memory. 
  for(i in 1:length(model)){
    table_LCA [i,1] <- paste("Model", i)
    table_LCA [i,2] <- model[[i]]$aic
    table_LCA [i,3] <- model[[i]]$bic
    table_LCA [i,4] <- model[[i]]$llik
    table_LCA [i,5] <- model[[i]]$Gsq
    error_prior <- entropy(model[[i]]$P)
    error_post <- mean(apply(model[[i]]$posterior,1, entropy),na.rm = TRUE)
    table_LCA [i,6] <- round(((error_prior-error_post) / error_prior),3)
    table_LCA [i,7] <- min(model[[i]]$P)*100
  }
  return(table_LCA)
}
set.seed(123)
wave1.test <- acl(acamslca, 6, f)
wave1.lca <- compare_classes_acl(wave1.test)
wave1.lca
```
# MIDUS 2 LCA
```{r, echo = FALSE, results = 'hide'}
# This chunk reads in the MIDUS2 Stata .dta file, subsets the data to only include CAMs, and restricts the data to complete cases. 

# Prayer and spiritual healing combined in stata.

# Read in MIDUS2 data and subset to complete cases on CAMs
# Read in stata file for MIDUS 2
path <- ("C:/Users/hanna/Documents/git/AHL/Stata/data-cleaning/MIDUS2.dta")
M2 <- read_dta(path)
bcamsList <- c("bcam1", "bcam2", "bcam3", "bcam4", "bcam5", "bcam6", "bcam7", 
               "bcam8", "bcam9", "bcam10", "bcam11", "bcam13", "bcam14", 
               "bcam21")

bcams <- M2[bcamsList] # Subset MIDUS2 - only include CAMs.

# Remove attributes from acams data - created in Stata (labels and data notes). They're (were) producing an error with bart_spher.
bcams <- remove_attributes(bcams, "label")
bcams <- remove_attributes(bcams, "notes")

str(bcams)
head(bcams)

# Rename columns 
bcams <- dplyr::rename(bcams, 
                         bAcupuncture = bcam1, 
                         bBiofeedback = bcam2,
                         bChiropractic = bcam3,
                         bEnergyHeal = bcam4,
                         bExerciseMove = bcam5,
                         bHerbal = bcam6,
                         bVitamins = bcam7,
                         bHomeopathy = bcam8,
                         bHypnosis = bcam9,
                         bImageryTech = bcam10,
                         bMassage = bcam11,
                         bRelaxMeditate = bcam13,
                         bSpecialDiet = bcam14,
                         bPraySpirit = bcam21)
head(bcams)
# Keep only complete cases
bcams=bcams[complete.cases(bcams),]

# Add 1 to each value so 1 = no and 2 = yes 
bcamslca <- bcams + 1
head (bcamslca)
str(bcams)
```
```{r, echo = FALSE}
f2 <- cbind(bAcupuncture, bBiofeedback, bChiropractic, bEnergyHeal, bExerciseMove, bHerbal, 
           bVitamins, bHomeopathy, bHypnosis, bImageryTech, bMassage, 
           bRelaxMeditate, bSpecialDiet, bPraySpirit) ~ 1
set.seed(123)
wave2.test <- acl(bcamslca, 6, f2)
compare_classes_acl(wave2.test)
wave2.lca
```
# MIDUS 3 LCA 
```{r, echo = FALSE, results = 'hide'}
# This chunk reads in the MIDUS2 Stata .dta file, subsets the data to only include CAMs, and restricts the data to complete cases. 

# Prayer and spiritual healing combined in stata.

# Read in MIDUS2 data and subset to complete cases on CAMs
# Read in stata file for MIDUS 2
path <- ("C:/Users/hanna/Documents/git/AHL/Stata/data-cleaning/MIDUS3.dta")
M3 <- read_dta(path)
ccamsList <- c("ccam1", "ccam2", "ccam3", "ccam4", "ccam5", "ccam6", "ccam7", 
               "ccam8", "ccam9", "ccam10", "ccam11", "ccam13", "ccam14",
               "ccam21")

ccams <- M3[ccamsList] # Subset MIDUS2 - only include CAMs.

# Remove attributes from acams data - created in Stata (labels and data notes). They're (were) producing an error with bart_spher.
ccams <- remove_attributes(ccams, "label")
ccams <- remove_attributes(ccams, "notes")

str(ccams)

# Create column that is the sum of CAMs used 
ctotalCams <- rowSums(ccams[,1:14])

ccams[sapply(ccams, is.numeric)] <- lapply(ccams[sapply(ccams, is.numeric)], as.factor) # convert all columns to factors

str(ccams) 
head(ccams)

# Rename columns 
ccams <- dplyr::rename(ccams, 
                        cAcupuncture = ccam1, 
                        cBiofeedback = ccam2,
                        cChiropractic = ccam3,
                        cEnergyHeal = ccam4,
                        cExerciseMove = ccam5,
                        cHerbal = ccam6,
                        cVitamins = ccam7,
                        cHomeopathy = ccam8,
                        cHypnosis = ccam9,
                        cImageryTech = ccam10,
                        cMassage = ccam11,
                        cRelaxMeditate = ccam13,
                        cSpecialDiet = ccam14, 
                        cPraySpirit = ccam21)
head(ccams)
# Keep only complete cases
ccams=ccams[complete.cases(ccams),]
str(ccams)
# Add 1 to each value so 1 = no and 2 = yes 
ccamslca <- ccams + 1
head (ccamslca)
str(ccams)
```

```{r, echo = FALSE}
f3 <- cbind(cAcupuncture, cBiofeedback, cChiropractic, cEnergyHeal, cExerciseMove, cHerbal, 
           aVitamins, cHomeopathy, cHypnosis, cImageryTech, cMassage, 
           aRelaxMeditate, cSpecialDiet, cPraySpirit) ~ 1
set.seed(123)
wave3.test <- acl(ccamslca, 6, f3)
wave3.lca <- compare_classes_acl(wave3.test)
wave3.lca
```